# Level Data: custom
# Generated by Platformer Level Editor

def load_map_custom():
    game_data = {
        'level_name': 'custom',
        'background_color': (173, 216, 230),
        'player_start_pos_p1': (90.5, 918.0),
        'player1_spawn_props': {'max_health': 100, 'move_speed': 350.0, 'jump_strength': -900.0, 'is_flipped_h': False, 'rotation': 0},
        'platforms_list': [{'rect': (0.0, 40.0, 40.0, 920.0), 'type': 'platform_wall_gray', 'color': (128, 128, 128), 'properties': {'destructible': False, 'health': 100, 'material_type': 'stone', 'corner_radius': 0, 'round_top_left': True, 'round_top_right': True, 'round_bottom_left': True, 'round_bottom_right': True, 'is_boundary': True}, 'is_flipped_h': False, 'rotation': 0}, {'rect': (0.0, 0.0, 1600.0, 40.0), 'type': 'platform_wall_gray', 'color': (128, 128, 128), 'properties': {'destructible': False, 'health': 100, 'material_type': 'stone', 'corner_radius': 0, 'round_top_left': True, 'round_top_right': True, 'round_bottom_left': True, 'round_bottom_right': True, 'is_boundary': True}, 'is_flipped_h': False, 'rotation': 0}, {'rect': (0.0, 960.0, 1600.0, 40.0), 'type': 'platform_wall_gray', 'color': (128, 128, 128), 'properties': {'destructible': False, 'health': 100, 'material_type': 'stone', 'corner_radius': 0, 'round_top_left': True, 'round_top_right': True, 'round_bottom_left': True, 'round_bottom_right': True, 'is_boundary': True}, 'is_flipped_h': False, 'rotation': 0}, {'rect': (1560.0, 40.0, 40.0, 920.0), 'type': 'platform_wall_gray', 'color': (128, 128, 128), 'properties': {'destructible': False, 'health': 100, 'material_type': 'stone', 'corner_radius': 0, 'round_top_left': True, 'round_top_right': True, 'round_bottom_left': True, 'round_bottom_right': True, 'is_boundary': True}, 'is_flipped_h': False, 'rotation': 0}],
        'ladders_list': [],
        'hazards_list': [],
        'background_tiles_list': [],
        'enemies_list': [],
        'items_list': [],
        'statues_list': [],
        'custom_images_list': [{'rect': (400.0, 320.0, 474.0, 629.0), 'source_file_path': 'Custom/OIP-C.jpg', 'original_width': 474, 'original_height': 629, 'layer_order': 0, 'properties': {'is_background': True, 'is_obstacle': False, 'destructible': False, 'health': 100, 'scroll_factor_x': 1.0, 'scroll_factor_y': 1.0, 'apply_gravity': False, 'opacity': 100}, 'is_flipped_h': False, 'rotation': 0}],
        'trigger_squares_list': [],
        'level_pixel_width': 1600.0,
        'level_min_x_absolute': 0.0,
        'level_min_y_absolute': 0.0,
        'level_max_y_absolute': 1000.0,
        'ground_level_y_ref': 1000.0,
        'ground_platform_height_ref': 40.0,
        'player_start_pos_p2': (170.5, 918.0),
        'player2_spawn_props': {'max_health': 100, 'move_speed': 350.0, 'jump_strength': -900.0, 'is_flipped_h': False, 'rotation': 0},
        'player_start_pos_p3': (250.5, 918.0),
        'player3_spawn_props': {'max_health': 100, 'move_speed': 350.0, 'jump_strength': -900.0, 'is_flipped_h': False, 'rotation': 0},
        'player_start_pos_p4': (330.5, 918.0),
        'player4_spawn_props': {'max_health': 100, 'move_speed': 350.0, 'jump_strength': -900.0, 'is_flipped_h': False, 'rotation': 0},
    }
    return game_data

if __name__ == '__main__':
    data = load_map_custom()
    import json
    print(json.dumps(data, indent=4))