# Level: 11
# Generated by Platformer Level Editor
import pygame
from tiles import Platform, Ladder, Lava
from statue import Statue
import constants as C

LEVEL_SPECIFIC_BACKGROUND_COLOR = (173, 216, 230)
player1_spawn_pos = (50, 758)
player1_spawn_props = {}

def load_map_11(initial_screen_width, initial_screen_height):
    """Loads the '11' level."""
    platforms = pygame.sprite.Group()
    ladders = pygame.sprite.Group()
    hazards = pygame.sprite.Group()
    enemy_spawns_data = []
    collectible_spawns_data = []
    statue_spawns_data = []

    platforms.add(Platform(280, 680, 560, 10, (0, 100, 0), platform_type='ledge'))
    platforms.add(Platform(0, 760, 1240, 80, (128, 128, 128), platform_type='wall'))
    platforms.add(Platform(180, 720, 20, 40, (128, 128, 128), platform_type='wall'))
    platforms.add(Platform(260, 640, 20, 40, (128, 128, 128), platform_type='wall'))
    platforms.add(Platform(820, 640, 20, 40, (128, 128, 128), platform_type='wall'))
    platforms.add(Platform(900.0, 720, 20, 40, (128, 128, 128), platform_type='wall'))
    # No ladders placed.
    # No hazards placed.
    enemy_spawns_data.append({'pos': (210, 758), 'patrol': None, 'enemy_color_id': 'green', 'properties': {}})
    enemy_spawns_data.append({'pos': (890, 758), 'patrol': None, 'enemy_color_id': 'green', 'properties': {}})
    enemy_spawns_data.append({'pos': (370, 678), 'patrol': None, 'enemy_color_id': 'green', 'properties': {}})
    enemy_spawns_data.append({'pos': (770, 678), 'patrol': None, 'enemy_color_id': 'green', 'properties': {}})
    # No collectible spawns defined.
    # No statue spawns defined.

    map_total_width_pixels = 1400
    level_min_y_absolute = 560
    level_max_y_absolute = 840
    main_ground_y_reference = 840
    main_ground_height_reference = 40

    _boundary_thickness = 80
    _boundary_wall_height = 440
    _boundary_color = (50, 50, 50)

    platforms.add(Platform(1240, 480, 160, 440, _boundary_color, platform_type='wall'))

    platforms.add(Platform(0, level_min_y_absolute - _boundary_thickness, 1400, _boundary_thickness, _boundary_color, platform_type="boundary_wall_top"))
    platforms.add(Platform(0, level_max_y_absolute, 1400, _boundary_thickness, _boundary_color, platform_type="boundary_wall_bottom"))
    platforms.add(Platform(0 - _boundary_thickness, level_min_y_absolute - _boundary_thickness, _boundary_thickness, _boundary_wall_height, _boundary_color, platform_type="boundary_wall_left"))
    platforms.add(Platform(map_total_width_pixels, level_min_y_absolute - _boundary_thickness, _boundary_thickness, _boundary_wall_height, _boundary_color, platform_type="boundary_wall_right"))

    print(f"Map 'load_map_11' loaded with: {len(platforms)} platforms, {len(ladders)} ladders, {len(hazards)} hazards, {len(statue_spawns_data)} statues.")
    return (platforms, ladders, hazards, enemy_spawns_data, collectible_spawns_data,
            player1_spawn_pos, player1_spawn_props,
            map_total_width_pixels, level_min_y_absolute, level_max_y_absolute,
            main_ground_y_reference, main_ground_height_reference,
            LEVEL_SPECIFIC_BACKGROUND_COLOR,
            statue_spawns_data)
