# Level: 11
# Generated by Platformer Level Editor (PySide6 Version)
import pygame 
from tiles import Platform, Ladder, Lava 
from statue import Statue 
import constants as C 

LEVEL_SPECIFIC_BACKGROUND_COLOR = (173, 216, 230) 
player1_spawn_pos = (316.0, 1720.0) 
player1_spawn_props = {} 

def load_map_11(initial_screen_width, initial_screen_height):
    platforms = pygame.sprite.Group()
    ladders = pygame.sprite.Group()
    hazards = pygame.sprite.Group()
    enemy_spawns_data = []      
    collectible_spawns_data = []
    statue_spawns_data = []     

    platforms.add(Platform(280.0, 680.0, 560.0, 10.0, (0, 100, 0), platform_type='ledge'))
    platforms.add(Platform(0.0, 760.0, 1240.0, 80.0, (128, 128, 128), platform_type='wall'))
    platforms.add(Platform(180.0, 720.0, 20.0, 40.0, (128, 128, 128), platform_type='wall'))
    platforms.add(Platform(260.0, 640.0, 20.0, 40.0, (128, 128, 128), platform_type='wall'))
    platforms.add(Platform(820.0, 640.0, 20.0, 40.0, (128, 128, 128), platform_type='wall'))
    platforms.add(Platform(900.0, 720.0, 20.0, 40.0, (128, 128, 128), platform_type='wall'))
    # No ladders placed.
    # No hazards placed.
    enemy_spawns_data.append({'pos': (476.0, 1720.0), 'patrol': None, 'enemy_color_id': 'green', 'properties': {}})
    enemy_spawns_data.append({'pos': (1156.0, 1720.0), 'patrol': None, 'enemy_color_id': 'green', 'properties': {}})
    enemy_spawns_data.append({'pos': (636.0, 1640.0), 'patrol': None, 'enemy_color_id': 'green', 'properties': {}})
    enemy_spawns_data.append({'pos': (1036.0, 1640.0), 'patrol': None, 'enemy_color_id': 'green', 'properties': {}})
    # No collectible spawns defined.
    # No statue spawns defined.

    map_total_width_pixels = 1592.0
    level_min_y_absolute = 560.0 
    level_max_y_absolute = 1720.0 
    main_ground_y_reference = 1720.0 
    main_ground_height_reference = 40.0

    _boundary_thickness = 40.0
    _boundary_wall_height = 1240.0
    _boundary_color = (50, 50, 50) 
    _effective_min_x_for_bounds = 0.0
    _boundary_full_width = 1592.0
    _filler_wall_y = 520.0
    _filler_wall_height = _boundary_wall_height 

    platforms.add(Platform(_effective_min_x_for_bounds, level_min_y_absolute - _boundary_thickness, _boundary_full_width, _boundary_thickness, _boundary_color, platform_type="boundary_wall_top"))
    platforms.add(Platform(_effective_min_x_for_bounds, level_max_y_absolute, _boundary_full_width, _boundary_thickness, _boundary_color, platform_type="boundary_wall_bottom"))
    platforms.add(Platform(_effective_min_x_for_bounds - _boundary_thickness, _filler_wall_y, _boundary_thickness, _filler_wall_height, _boundary_color, platform_type="boundary_wall_left"))
    platforms.add(Platform(map_total_width_pixels, _filler_wall_y, _boundary_thickness, _filler_wall_height, _boundary_color, platform_type="boundary_wall_right"))

    print(f"Map 'load_map_11' loaded. Platforms: {len(platforms)}, Ladders: {len(ladders)}, Hazards: {len(hazards)}, Statues: {len(statue_spawns_data)}")
    return (platforms, ladders, hazards, enemy_spawns_data, collectible_spawns_data,
            player1_spawn_pos, player1_spawn_props,
            map_total_width_pixels, level_min_y_absolute, level_max_y_absolute,
            main_ground_y_reference, main_ground_height_reference,
            LEVEL_SPECIFIC_BACKGROUND_COLOR,
            statue_spawns_data)
