# Level Data: 4p2
# Generated by Platformer Level Editor

def load_map_4p2():
    game_data = {
        'level_name': '4p2',
        'background_color': (173, 216, 230),
        'player_start_pos_p1': (610.5, 918.0),
        'player1_spawn_props': {'max_health': 100, 'move_speed': 350.0, 'jump_strength': -900.0},
        'player_start_pos_p2': (650.5, 918.0),
        'player2_spawn_props': {'max_health': 100, 'move_speed': 350.0, 'jump_strength': -900.0},
        'player_start_pos_p3': (690.5, 878.0),
        'player3_spawn_props': {'max_health': 100, 'move_speed': 350.0, 'jump_strength': -900.0},
        'player_start_pos_p4': (730.5, 918.0),
        'player4_spawn_props': {'max_health': 100, 'move_speed': 350.0, 'jump_strength': -900.0},
        'platforms_list': [{'rect': (0.0, 80.0, 80.0, 840.0), 'type': 'platform_wall_gray', 'color': (128, 128, 128), 'properties': {'is_boundary': True}}, {'rect': (0.0, 0.0, 1600.0, 80.0), 'type': 'platform_wall_gray', 'color': (128, 128, 128), 'properties': {'is_boundary': True}}, {'rect': (0.0, 920.0, 1600.0, 80.0), 'type': 'platform_wall_gray', 'color': (128, 128, 128), 'properties': {'is_boundary': True}}, {'rect': (1520.0, 80.0, 80.0, 840.0), 'type': 'platform_wall_gray', 'color': (128, 128, 128), 'properties': {'is_boundary': True}}],
        'ladders_list': [],
        'hazards_list': [],
        'background_tiles_list': [],
        'enemies_list': [],
        'items_list': [],
        'statues_list': [],
        'level_pixel_width': 1600.0,
        'level_min_x_absolute': 0.0,
        'level_min_y_absolute': 0.0,
        'level_max_y_absolute': 1000.0,
        'ground_level_y_ref': 920.0,
        'ground_platform_height_ref': 80.0,
    }
    return game_data

if __name__ == '__main__':
    data = load_map_4p2()
    import json
    print(json.dumps(data, indent=4))