# Level Data: 4players
# Generated by Platformer Level Editor

def load_map_4players():
    game_data = {
        'level_name': '4players',
        'background_color': (173, 216, 230),
        'player_start_pos_p1': (450.5, 918.0),
        'player1_spawn_props': {'max_health': 100, 'move_speed': 350.0, 'jump_strength': -900.0},
        'player_start_pos_p2': (490.5, 878.0),
        'player2_spawn_props': {'max_health': 100, 'move_speed': 350.0, 'jump_strength': -900.0},
        'platforms_list': [{'rect': (240.0, 880.0, 120.0, 10.0), 'type': 'platform_ledge_gray_one_fourth', 'color': (85, 85, 255), 'properties': {}}, {'rect': (0.0, 80.0, 80.0, 840.0), 'type': 'platform_wall_gray', 'color': (128, 128, 128), 'properties': {'is_boundary': True}}, {'rect': (0.0, 0.0, 1600.0, 80.0), 'type': 'platform_wall_gray', 'color': (128, 128, 128), 'properties': {'is_boundary': True}}, {'rect': (0.0, 920.0, 1600.0, 80.0), 'type': 'platform_wall_gray', 'color': (128, 128, 128), 'properties': {'is_boundary': True}}, {'rect': (320.0, 760.0, 40.0, 120.0), 'type': 'platform_wall_gray', 'color': (128, 128, 128), 'properties': {}}, {'rect': (320.0, 720.0, 200.0, 40.0), 'type': 'platform_wall_gray', 'color': (128, 128, 128), 'properties': {}}, {'rect': (480.0, 680.0, 200.0, 40.0), 'type': 'platform_wall_gray', 'color': (128, 128, 128), 'properties': {}}, {'rect': (640.0, 720.0, 40.0, 40.0), 'type': 'platform_wall_gray', 'color': (128, 128, 128), 'properties': {}}, {'rect': (640.0, 760.0, 80.0, 40.0), 'type': 'platform_wall_gray', 'color': (128, 128, 128), 'properties': {}}, {'rect': (680.0, 800.0, 40.0, 120.0), 'type': 'platform_wall_gray', 'color': (128, 128, 128), 'properties': {}}, {'rect': (960.0, 640.0, 40.0, 280.0), 'type': 'platform_wall_gray', 'color': (128, 128, 128), 'properties': {}}, {'rect': (1520.0, 80.0, 80.0, 840.0), 'type': 'platform_wall_gray', 'color': (128, 128, 128), 'properties': {'is_boundary': True}}],
        'ladders_list': [],
        'hazards_list': [{'rect': (720.0, 880.0, 80.0, 42.0), 'type': 'hazard_lava', 'color': (255, 69, 0), 'properties': {}}],
        'background_tiles_list': [],
        'enemies_list': [{'start_pos': (1090.5, 918.0), 'type': 'enemy_pink', 'properties': {'health': 10, 'move_speed': 120.0, 'patrol_behavior': 'hover_patrol'}}],
        'items_list': [{'type': 'chest', 'pos': (381.0, 665.0), 'properties': {'item_type': 'coin', 'item_quantity': 1}}],
        'statues_list': [{'id': 'statue_0', 'pos': (176.5, 898.0), 'properties': {'destructible': True, 'hardness': 1}}],
        'level_pixel_width': 1600.0,
        'level_min_x_absolute': 0.0,
        'level_min_y_absolute': 0.0,
        'level_max_y_absolute': 1000.0,
        'ground_level_y_ref': 920.0,
        'ground_platform_height_ref': 80.0,
    }
    return game_data

if __name__ == '__main__':
    data = load_map_4players()
    import json
    print(json.dumps(data, indent=4))