# Level: bigmap1
# Generated by Platformer Level Editor (Optimized Export)
import pygame
from tiles import Platform, Ladder, Lava
import constants as C

LEVEL_SPECIFIC_BACKGROUND_COLOR = (173, 216, 230)

def load_map_bigmap1(initial_screen_width, initial_screen_height):
    """
    Loads the 'bigmap1' level.
    """
    print(f"Loading map: load_map_bigmap1...")
    platforms = pygame.sprite.Group()
    ladders = pygame.sprite.Group()
    hazards = pygame.sprite.Group()
    enemy_spawns_data = []
    collectible_spawns_data = []

    player1_spawn = (89.0, 1917.0)

    # --- Placed Objects (merged where possible) ---
    platforms.add(Platform(160, 1880.0, 80, 13, (0,100,0), platform_type='ledge'))
    platforms.add(Platform(240, 1880, 40, 10, (0,100,0), platform_type='ledge'))
    platforms.add(Platform(0, 600, 80, 200, (128,128,128), platform_type='wall'))
    platforms.add(Platform(0, 1160.0, 80, 120, (128,128,128), platform_type='wall'))
    platforms.add(Platform(0, 1360.0, 80, 560, (128,128,128), platform_type='wall'))
    platforms.add(Platform(0, 0, 120, 600, (128,128,128), platform_type='wall'))
    platforms.add(Platform(0, 800.0, 120, 360, (128,128,128), platform_type='wall'))
    platforms.add(Platform(0, 1280.0, 120, 80, (128,128,128), platform_type='wall'))
    platforms.add(Platform(0, 1920.0, 360, 40, (128,128,128), platform_type='wall'))
    platforms.add(Platform(0, 1960.0, 4040, 40, (128,128,128), platform_type='wall'))
    platforms.add(Platform(80, 2000, 640, 40, (128,128,128), platform_type='wall'))
    platforms.add(Platform(680, 1920, 80, 40, (128,128,128), platform_type='wall'))
    platforms.add(Platform(960.0, 2000, 200, 40, (128,128,128), platform_type='wall'))
    platforms.add(Platform(1200.0, 1920.0, 1680, 40, (128,128,128), platform_type='wall'))
    platforms.add(Platform(1280.0, 2000.0, 80, 40, (128,128,128), platform_type='wall'))
    platforms.add(Platform(1400.0, 2000.0, 360, 40, (128,128,128), platform_type='wall'))
    platforms.add(Platform(1760.0, 1880, 80, 40, (128,128,128), platform_type='wall'))
    platforms.add(Platform(2080.0, 2000, 120, 40, (128,128,128), platform_type='wall'))
    platforms.add(Platform(2120.0, 1880, 120, 40, (128,128,128), platform_type='wall'))
    platforms.add(Platform(2520.0, 1880, 120, 40, (128,128,128), platform_type='wall'))
    platforms.add(Platform(2600.0, 2000, 80, 40, (128,128,128), platform_type='wall'))
    platforms.add(Platform(2760.0, 2000, 320, 40, (128,128,128), platform_type='wall'))
    platforms.add(Platform(3040.0, 1920, 320, 40, (128,128,128), platform_type='wall'))
    platforms.add(Platform(3360.0, 2000, 280, 40, (128,128,128), platform_type='wall'))
    platforms.add(Platform(3400.0, 1920, 80, 40, (128,128,128), platform_type='wall'))
    platforms.add(Platform(3560.0, 1880.0, 80, 40, (128,128,128), platform_type='wall'))
    platforms.add(Platform(3560.0, 1920.0, 480, 40, (128,128,128), platform_type='wall'))
    platforms.add(Platform(3760, 2000, 80, 40, (128,128,128), platform_type='wall'))
    platforms.add(Platform(3800.0, 1880.0, 240, 40, (128,128,128), platform_type='wall'))
    platforms.add(Platform(3840.0, 1840.0, 200, 40, (128,128,128), platform_type='wall'))
    platforms.add(Platform(3920.0, 0, 80, 1600, (128,128,128), platform_type='wall'))
    platforms.add(Platform(3920, 1600.0, 120, 80, (128,128,128), platform_type='wall'))
    platforms.add(Platform(3920.0, 2000, 120, 40, (128,128,128), platform_type='wall'))
    platforms.add(Platform(3960, 1680.0, 80, 160, (128,128,128), platform_type='wall'))
    # No ladders placed.
    hazards.add(Lava(880.0, 1920, 40, 40, (255,69,0)))
    hazards.add(Lava(920.0, 1920, 40, 40, (255,69,0)))
    hazards.add(Lava(1000.0, 1920, 40, 40, (255,69,0)))
    hazards.add(Lava(1040.0, 1920, 40, 40, (255,69,0)))
    hazards.add(Lava(960.0, 1920, 40, 40, (255,69,0)))
    hazards.add(Lava(1080.0, 1920, 40, 40, (255,69,0)))
    hazards.add(Lava(1120.0, 1920, 40, 40, (255,69,0)))
    hazards.add(Lava(840.0, 1920, 40, 40, (255,69,0)))
    hazards.add(Lava(800.0, 1920, 40, 40, (255,69,0)))
    hazards.add(Lava(760.0, 1920, 40, 40, (255,69,0)))
    hazards.add(Lava(1160.0, 1920, 40, 40, (255,69,0)))
    enemy_spawns_data.append({'pos': (329, 1917), 'patrol': None, 'enemy_color_id': 'yellow'})
    enemy_spawns_data.append({'pos': (369, 1957), 'patrol': None, 'enemy_color_id': 'red'})
    enemy_spawns_data.append({'pos': (409, 1957), 'patrol': None, 'enemy_color_id': 'purple'})
    enemy_spawns_data.append({'pos': (449, 1957), 'patrol': None, 'enemy_color_id': 'pink'})
    enemy_spawns_data.append({'pos': (489, 1957.0), 'patrol': None, 'enemy_color_id': 'green'})
    collectible_spawns_data.append({'type': 'chest', 'pos': (1306.0, 1919)})

    # --- Level Dimensions for Game Camera & Boundaries ---
    map_total_width_pixels = 4200
    level_min_y_absolute = -80
    level_max_y_absolute = 2040
    main_ground_y_reference = 2040
    main_ground_height_reference = 40

    _boundary_thickness = C.TILE_SIZE * 2
    _boundary_wall_height = level_max_y_absolute - level_min_y_absolute + (2 * _boundary_thickness)
    _boundary_color = getattr(C, 'DARK_GRAY', (50,50,50))

    # Filler wall on the right to ensure no empty background padding
    platforms.add(Platform(4040, level_min_y_absolute - _boundary_thickness, 160, _boundary_wall_height, _boundary_color, platform_type='wall'))

    # Boundary platforms (these define the absolute edges of the level area)
    # Top boundary (ceiling)
    platforms.add(Platform(0, level_min_y_absolute - _boundary_thickness, map_total_width_pixels, _boundary_thickness, _boundary_color, platform_type="boundary_wall_top"))
    # Bottom boundary (floor/kill plane)
    platforms.add(Platform(0, level_max_y_absolute, map_total_width_pixels, _boundary_thickness, _boundary_color, platform_type="boundary_wall_bottom"))
    # Left boundary
    platforms.add(Platform(-_boundary_thickness, level_min_y_absolute - _boundary_thickness, _boundary_thickness, _boundary_wall_height, _boundary_color, platform_type="boundary_wall_left"))
    # Right boundary (placed at the very edge of map_total_width_pixels)
    platforms.add(Platform(map_total_width_pixels, level_min_y_absolute - _boundary_thickness, _boundary_thickness, _boundary_wall_height, _boundary_color, platform_type="boundary_wall_right"))

    print(f"Map 'load_map_bigmap1' loaded with: {len(platforms)} platforms, {len(ladders)} ladders, {len(hazards)} hazards.")
    return (platforms, ladders, hazards, enemy_spawns_data, collectible_spawns_data,
            player1_spawn,
            map_total_width_pixels, level_min_y_absolute, level_max_y_absolute,
            main_ground_y_reference, main_ground_height_reference,
            LEVEL_SPECIFIC_BACKGROUND_COLOR)