# Level Data: bowl
# Generated by Platformer Level Editor
# This file contains data structures that can be loaded by the game engine.
# It does not instantiate game objects directly.

def get_map_data_bowl():
    level_data = {
        "map_name": 'bowl',
        "background_color": (173, 216, 230),
        "player1_spawn_pos": (10020, 19960),
        "player1_spawn_props": {},
        "platforms_data": [{'x': 0.0, 'y': -120.0, 'w': 20160.0, 'h': 40.0, 'color': (50, 50, 50), 'type': 'boundary_wall_top'}, {'x': 0.0, 'y': 20000.0, 'w': 20160.0, 'h': 40.0, 'color': (50, 50, 50), 'type': 'boundary_wall_bottom'}, {'x': -40.0, 'y': -120.0, 'w': 40.0, 'h': 20160.0, 'color': (50, 50, 50), 'type': 'boundary_wall_left'}, {'x': 20160.0, 'y': -120.0, 'w': 40.0, 'h': 20160.0, 'color': (50, 50, 50), 'type': 'boundary_wall_right'}],
        "ladders_data": [],
        "hazards_data": [],
        "enemy_spawns_data": [],
        "collectible_spawns_data": [],
        "statue_spawns_data": [],
        "dimensions_data": {'map_total_width_pixels': 20160.0, 'level_min_y_absolute': -80.0, 'level_max_y_absolute': 20000.0, 'main_ground_y_reference': 20000.0, 'main_ground_height_reference': 40.0}
    }
    return level_data

if __name__ == '__main__':
    # Example of how to load and print the data
    data = get_map_data_bowl()
    import json
    print(json.dumps(data, indent=4))
