# Level: centertower1
# Generated by Platformer Level Editor
import pygame
from tiles import Platform, Ladder, Lava
from statue import Statue
import constants as C

LEVEL_SPECIFIC_BACKGROUND_COLOR = (173, 216, 230)
player1_spawn_pos = (490.0, 758.0)
player1_spawn_props = {}

def load_map_centertower1(initial_screen_width, initial_screen_height):
    """Loads the 'centertower1' level."""
    platforms = pygame.sprite.Group()
    ladders = pygame.sprite.Group()
    hazards = pygame.sprite.Group()
    enemy_spawns_data = []
    collectible_spawns_data = []
    statue_spawns_data = []

    platforms.add(Platform(0, 0, 80, 760, (128, 128, 128), platform_type='wall'))
    platforms.add(Platform(0, 760, 1240, 80, (128, 128, 128), platform_type='wall'))
    platforms.add(Platform(320.0, 720, 140, 40, (128, 128, 128), platform_type='wall'))
    platforms.add(Platform(360.0, 680, 100, 40, (128, 128, 128), platform_type='wall'))
    platforms.add(Platform(400, 640.0, 60, 40, (128, 128, 128), platform_type='wall'))
    platforms.add(Platform(440, 520, 20, 120, (128, 128, 128), platform_type='wall'))
    platforms.add(Platform(560, 560, 20, 200, (128, 128, 128), platform_type='wall'))
    platforms.add(Platform(560.0, 640, 80, 80, (128, 128, 128), platform_type='wall'))
    platforms.add(Platform(560.0, 720, 120, 40, (128, 128, 128), platform_type='wall'))
    platforms.add(Platform(1120.0, 0, 80, 760, (128, 128, 128), platform_type='wall'))
    # No ladders placed.
    # No hazards placed.
    enemy_spawns_data.append({'pos': (730.0, 678), 'patrol': None, 'enemy_color_id': 'pink', 'properties': {}})
    enemy_spawns_data.append({'pos': (730.0, 718), 'patrol': None, 'enemy_color_id': 'pink', 'properties': {}})
    enemy_spawns_data.append({'pos': (930.0, 718), 'patrol': None, 'enemy_color_id': 'pink', 'properties': {}})
    enemy_spawns_data.append({'pos': (1130.0, 758.0), 'patrol': None, 'enemy_color_id': 'pink', 'properties': {}})
    # No collectible spawns defined.
    # No statue spawns defined.

    map_total_width_pixels = 1400
    level_min_y_absolute = -80
    level_max_y_absolute = 840
    main_ground_y_reference = 840
    main_ground_height_reference = 40

    _boundary_thickness = 80
    _boundary_wall_height = 1080
    _boundary_color = (50, 50, 50)

    platforms.add(Platform(1240, -160, 160, 1080, _boundary_color, platform_type='wall'))

    platforms.add(Platform(0, level_min_y_absolute - _boundary_thickness, 1400, _boundary_thickness, _boundary_color, platform_type="boundary_wall_top"))
    platforms.add(Platform(0, level_max_y_absolute, 1400, _boundary_thickness, _boundary_color, platform_type="boundary_wall_bottom"))
    platforms.add(Platform(0 - _boundary_thickness, level_min_y_absolute - _boundary_thickness, _boundary_thickness, _boundary_wall_height, _boundary_color, platform_type="boundary_wall_left"))
    platforms.add(Platform(map_total_width_pixels, level_min_y_absolute - _boundary_thickness, _boundary_thickness, _boundary_wall_height, _boundary_color, platform_type="boundary_wall_right"))

    print(f"Map 'load_map_centertower1' loaded with: {len(platforms)} platforms, {len(ladders)} ladders, {len(hazards)} hazards, {len(statue_spawns_data)} statues.")
    return (platforms, ladders, hazards, enemy_spawns_data, collectible_spawns_data,
            player1_spawn_pos, player1_spawn_props,
            map_total_width_pixels, level_min_y_absolute, level_max_y_absolute,
            main_ground_y_reference, main_ground_height_reference,
            LEVEL_SPECIFIC_BACKGROUND_COLOR,
            statue_spawns_data)
