# Level Data: centertower1
# Generated by Platformer Level Editor
# This file contains data structures that can be loaded by the game engine.
# It does not instantiate game objects directly.

def get_map_data_centertower1():
    level_data = {
        "map_name": 'centertower1',
        "background_color": (173, 216, 230),
        "player1_spawn_pos": (490.5, 758.0),
        "player1_spawn_props": {},
        "platforms_data": [{'x': 0.0, 'y': 0.0, 'w': 80.0, 'h': 760.0, 'color': (128, 128, 128), 'type': 'wall'}, {'x': 0.0, 'y': 760.0, 'w': 1240.0, 'h': 80.0, 'color': (128, 128, 128), 'type': 'wall'}, {'x': 320.0, 'y': 720.0, 'w': 140.0, 'h': 40.0, 'color': (128, 128, 128), 'type': 'wall'}, {'x': 360.0, 'y': 680.0, 'w': 100.0, 'h': 40.0, 'color': (128, 128, 128), 'type': 'wall'}, {'x': 400.0, 'y': 640.0, 'w': 60.0, 'h': 40.0, 'color': (128, 128, 128), 'type': 'wall'}, {'x': 440.0, 'y': 520.0, 'w': 20.0, 'h': 120.0, 'color': (128, 128, 128), 'type': 'wall'}, {'x': 560.0, 'y': 560.0, 'w': 20.0, 'h': 200.0, 'color': (128, 128, 128), 'type': 'wall'}, {'x': 560.0, 'y': 640.0, 'w': 80.0, 'h': 80.0, 'color': (128, 128, 128), 'type': 'wall'}, {'x': 560.0, 'y': 720.0, 'w': 120.0, 'h': 40.0, 'color': (128, 128, 128), 'type': 'wall'}, {'x': 1120.0, 'y': 0.0, 'w': 80.0, 'h': 760.0, 'color': (128, 128, 128), 'type': 'wall'}, {'x': 0.0, 'y': -120.0, 'w': 1400.0, 'h': 40.0, 'color': (50, 50, 50), 'type': 'boundary_wall_top'}, {'x': 0.0, 'y': 840.0, 'w': 1400.0, 'h': 40.0, 'color': (50, 50, 50), 'type': 'boundary_wall_bottom'}, {'x': -40.0, 'y': -120.0, 'w': 40.0, 'h': 1000.0, 'color': (50, 50, 50), 'type': 'boundary_wall_left'}, {'x': 1400.0, 'y': -120.0, 'w': 40.0, 'h': 1000.0, 'color': (50, 50, 50), 'type': 'boundary_wall_right'}],
        "ladders_data": [],
        "hazards_data": [],
        "enemy_spawns_data": [{'pos': (730.5, 678.0), 'patrol': None, 'enemy_color_id': 'pink', 'properties': {}}, {'pos': (730.5, 718.0), 'patrol': None, 'enemy_color_id': 'pink', 'properties': {}}, {'pos': (930.5, 718.0), 'patrol': None, 'enemy_color_id': 'pink', 'properties': {}}, {'pos': (1130.5, 758.0), 'patrol': None, 'enemy_color_id': 'pink', 'properties': {}}],
        "collectible_spawns_data": [],
        "statue_spawns_data": [],
        "dimensions_data": {'map_total_width_pixels': 1400.0, 'level_min_y_absolute': -80.0, 'level_max_y_absolute': 840.0, 'main_ground_y_reference': 840.0, 'main_ground_height_reference': 40.0}
    }
    return level_data

if __name__ == '__main__':
    # Example of how to load and print the data
    data = get_map_data_centertower1()
    import json
    print(json.dumps(data, indent=4))
