# Level: idk
# Generated by Platformer Level Editor
import pygame
from tiles import Platform, Ladder, Lava
from statue import Statue
import constants as C

LEVEL_SPECIFIC_BACKGROUND_COLOR = (205, 255, 248)
player1_spawn_pos = (450, 438)
player1_spawn_props = {}

def load_map_idk(initial_screen_width, initial_screen_height):
    """Loads the 'idk' level."""
    platforms = pygame.sprite.Group()
    ladders = pygame.sprite.Group()
    hazards = pygame.sprite.Group()
    enemy_spawns_data = []
    collectible_spawns_data = []
    statue_spawns_data = []

    platforms.add(Platform(120, 640, 320, 40, (128, 128, 128), platform_type='wall'))
    platforms.add(Platform(320, 440, 720, 80, (128, 128, 128), platform_type='wall'))
    platforms.add(Platform(960, 640.0, 240, 40, (128, 128, 128), platform_type='wall'))
    # No ladders placed.
    hazards.add(Lava(280, 240.0, 40, 41, (255, 69, 0)))
    hazards.add(Lava(280, 280.0, 40, 41, (255, 69, 0)))
    hazards.add(Lava(280, 320.0, 40, 41, (255, 69, 0)))
    hazards.add(Lava(280, 360.0, 40, 41, (255, 69, 0)))
    hazards.add(Lava(280, 400.0, 40, 41, (255, 69, 0)))
    hazards.add(Lava(280, 440.0, 40, 41, (255, 69, 0)))
    hazards.add(Lava(280, 480.0, 40, 41, (255, 69, 0)))
    hazards.add(Lava(1000.0, 160.0, 40, 41, (255, 69, 0)))
    hazards.add(Lava(1000.0, 200.0, 40, 41, (255, 69, 0)))
    hazards.add(Lava(1000.0, 240.0, 40, 41, (255, 69, 0)))
    hazards.add(Lava(1000.0, 280.0, 40, 41, (255, 69, 0)))
    hazards.add(Lava(1000.0, 320.0, 40, 41, (255, 69, 0)))
    hazards.add(Lava(1000.0, 360.0, 40, 41, (255, 69, 0)))
    hazards.add(Lava(1000.0, 400.0, 40, 41, (255, 69, 0)))
    enemy_spawns_data.append({'pos': (50, 758.0), 'patrol': None, 'enemy_color_id': 'yellow', 'properties': {}})
    enemy_spawns_data.append({'pos': (130, 758.0), 'patrol': None, 'enemy_color_id': 'red', 'properties': {}})
    enemy_spawns_data.append({'pos': (210, 758.0), 'patrol': None, 'enemy_color_id': 'purple', 'properties': {}})
    enemy_spawns_data.append({'pos': (290.0, 758), 'patrol': None, 'enemy_color_id': 'pink', 'properties': {}})
    enemy_spawns_data.append({'pos': (370, 718), 'patrol': None, 'enemy_color_id': 'green', 'properties': {}})
    enemy_spawns_data.append({'pos': (410.0, 758), 'patrol': None, 'enemy_color_id': 'gray', 'properties': {}})
    enemy_spawns_data.append({'pos': (450, 798), 'patrol': None, 'enemy_color_id': 'purple', 'properties': {}})
    enemy_spawns_data.append({'pos': (490, 798), 'patrol': None, 'enemy_color_id': 'purple', 'properties': {}})
    enemy_spawns_data.append({'pos': (530, 798), 'patrol': None, 'enemy_color_id': 'purple', 'properties': {}})
    enemy_spawns_data.append({'pos': (570, 798), 'patrol': None, 'enemy_color_id': 'purple', 'properties': {}})
    enemy_spawns_data.append({'pos': (610, 798), 'patrol': None, 'enemy_color_id': 'purple', 'properties': {}})
    enemy_spawns_data.append({'pos': (650, 798), 'patrol': None, 'enemy_color_id': 'purple', 'properties': {}})
    enemy_spawns_data.append({'pos': (690, 798), 'patrol': None, 'enemy_color_id': 'purple', 'properties': {}})
    enemy_spawns_data.append({'pos': (730, 798), 'patrol': None, 'enemy_color_id': 'purple', 'properties': {}})
    enemy_spawns_data.append({'pos': (770, 798), 'patrol': None, 'enemy_color_id': 'purple', 'properties': {}})
    enemy_spawns_data.append({'pos': (810, 798), 'patrol': None, 'enemy_color_id': 'purple', 'properties': {}})
    enemy_spawns_data.append({'pos': (850, 798), 'patrol': None, 'enemy_color_id': 'purple', 'properties': {}})
    enemy_spawns_data.append({'pos': (890, 798), 'patrol': None, 'enemy_color_id': 'purple', 'properties': {}})
    enemy_spawns_data.append({'pos': (930, 798), 'patrol': None, 'enemy_color_id': 'purple', 'properties': {}})
    enemy_spawns_data.append({'pos': (970, 798), 'patrol': None, 'enemy_color_id': 'purple', 'properties': {}})
    collectible_spawns_data.append({'type': 'chest', 'pos': (675.0, 450.0), 'properties': {}})
    # No statue spawns defined.

    map_total_width_pixels = 1320
    level_min_y_absolute = 80
    level_max_y_absolute = 798
    main_ground_y_reference = 798
    main_ground_height_reference = 40

    _boundary_thickness = 80
    _boundary_wall_height = 878
    _boundary_color = (50, 50, 50)

    platforms.add(Platform(1200, 0, 120, 878, _boundary_color, platform_type='wall'))

    platforms.add(Platform(0, level_min_y_absolute - _boundary_thickness, 1320, _boundary_thickness, _boundary_color, platform_type="boundary_wall_top"))
    platforms.add(Platform(0, level_max_y_absolute, 1320, _boundary_thickness, _boundary_color, platform_type="boundary_wall_bottom"))
    platforms.add(Platform(0 - _boundary_thickness, level_min_y_absolute - _boundary_thickness, _boundary_thickness, _boundary_wall_height, _boundary_color, platform_type="boundary_wall_left"))
    platforms.add(Platform(map_total_width_pixels, level_min_y_absolute - _boundary_thickness, _boundary_thickness, _boundary_wall_height, _boundary_color, platform_type="boundary_wall_right"))

    print(f"Map 'load_map_idk' loaded with: {len(platforms)} platforms, {len(ladders)} ladders, {len(hazards)} hazards, {len(statue_spawns_data)} statues.")
    return (platforms, ladders, hazards, enemy_spawns_data, collectible_spawns_data,
            player1_spawn_pos, player1_spawn_props,
            map_total_width_pixels, level_min_y_absolute, level_max_y_absolute,
            main_ground_y_reference, main_ground_height_reference,
            LEVEL_SPECIFIC_BACKGROUND_COLOR,
            statue_spawns_data)
