# Level: idk
# Generated by Platformer Level Editor (Optimized Export)
import pygame
from tiles import Platform, Ladder, Lava
import constants as C

LEVEL_SPECIFIC_BACKGROUND_COLOR = (173, 216, 230)

def load_map_idk(initial_screen_width, initial_screen_height):
    """
    Loads the 'idk' level.
    """
    print(f"Loading map: load_map_idk...")
    platforms = pygame.sprite.Group()
    ladders = pygame.sprite.Group()
    hazards = pygame.sprite.Group()
    enemy_spawns_data = []
    collectible_spawns_data = []

    player1_spawn = (450, 438)

    # --- Placed Objects (merged where possible) ---
    platforms.add(Platform(120, 640, 320, 40, (128,128,128), platform_type='wall'))
    platforms.add(Platform(320, 440, 720, 80, (128,128,128), platform_type='wall'))
    platforms.add(Platform(960, 640.0, 240, 40, (128,128,128), platform_type='wall'))
    # No ladders placed.
    hazards.add(Lava(280, 240.0, 40, 41, (255,69,0)))
    hazards.add(Lava(280, 280.0, 40, 41, (255,69,0)))
    hazards.add(Lava(280, 320.0, 40, 41, (255,69,0)))
    hazards.add(Lava(280, 360.0, 40, 41, (255,69,0)))
    hazards.add(Lava(280, 400.0, 40, 41, (255,69,0)))
    hazards.add(Lava(280, 440.0, 40, 41, (255,69,0)))
    hazards.add(Lava(280, 480.0, 40, 41, (255,69,0)))
    hazards.add(Lava(1000.0, 160.0, 40, 41, (255,69,0)))
    hazards.add(Lava(1000.0, 200.0, 40, 41, (255,69,0)))
    hazards.add(Lava(1000.0, 240.0, 40, 41, (255,69,0)))
    hazards.add(Lava(1000.0, 280.0, 40, 41, (255,69,0)))
    hazards.add(Lava(1000.0, 320.0, 40, 41, (255,69,0)))
    hazards.add(Lava(1000.0, 360.0, 40, 41, (255,69,0)))
    hazards.add(Lava(1000.0, 400.0, 40, 41, (255,69,0)))
    enemy_spawns_data.append({'pos': (50, 758.0), 'patrol': None, 'enemy_color_id': 'yellow'})
    enemy_spawns_data.append({'pos': (130, 758.0), 'patrol': None, 'enemy_color_id': 'red'})
    enemy_spawns_data.append({'pos': (210, 758.0), 'patrol': None, 'enemy_color_id': 'purple'})
    enemy_spawns_data.append({'pos': (290.0, 758), 'patrol': None, 'enemy_color_id': 'pink'})
    enemy_spawns_data.append({'pos': (370, 718), 'patrol': None, 'enemy_color_id': 'green'})
    enemy_spawns_data.append({'pos': (410.0, 758), 'patrol': None, 'enemy_color_id': 'gray'})
    collectible_spawns_data.append({'type': 'chest', 'pos': (675.0, 450.0)})

    # --- Level Dimensions for Game Camera & Boundaries ---
    map_total_width_pixels = 1320
    level_min_y_absolute = 80
    level_max_y_absolute = 758
    main_ground_y_reference = 758
    main_ground_height_reference = 40

    _boundary_thickness = C.TILE_SIZE * 2
    _boundary_wall_height = level_max_y_absolute - level_min_y_absolute + (2 * _boundary_thickness)
    _boundary_color = getattr(C, 'DARK_GRAY', (50,50,50))

    # Filler wall on the right to ensure no empty background padding
    platforms.add(Platform(1200, level_min_y_absolute - _boundary_thickness, 120, _boundary_wall_height, _boundary_color, platform_type='wall'))

    # Boundary platforms (these define the absolute edges of the level area)
    # Top boundary (ceiling)
    platforms.add(Platform(0, level_min_y_absolute - _boundary_thickness, map_total_width_pixels, _boundary_thickness, _boundary_color, platform_type="boundary_wall_top"))
    # Bottom boundary (floor/kill plane)
    platforms.add(Platform(0, level_max_y_absolute, map_total_width_pixels, _boundary_thickness, _boundary_color, platform_type="boundary_wall_bottom"))
    # Left boundary
    platforms.add(Platform(-_boundary_thickness, level_min_y_absolute - _boundary_thickness, _boundary_thickness, _boundary_wall_height, _boundary_color, platform_type="boundary_wall_left"))
    # Right boundary (placed at the very edge of map_total_width_pixels)
    platforms.add(Platform(map_total_width_pixels, level_min_y_absolute - _boundary_thickness, _boundary_thickness, _boundary_wall_height, _boundary_color, platform_type="boundary_wall_right"))

    print(f"Map 'load_map_idk' loaded with: {len(platforms)} platforms, {len(ladders)} ladders, {len(hazards)} hazards.")
    return (platforms, ladders, hazards, enemy_spawns_data, collectible_spawns_data,
            player1_spawn,
            map_total_width_pixels, level_min_y_absolute, level_max_y_absolute,
            main_ground_y_reference, main_ground_height_reference,
            LEVEL_SPECIFIC_BACKGROUND_COLOR)