# Level Data: idk
# Generated by Platformer Level Editor
# This file contains data structures that can be loaded by the game engine.
# It does not instantiate game objects directly.

def get_map_data_idk():
    level_data = {
        "map_name": 'idk',
        "background_color": (205, 255, 248),
        "player1_spawn_pos": (450.5, 438.0),
        "player1_spawn_props": {},
        "platforms_data": [{'x': 120.0, 'y': 640.0, 'w': 320.0, 'h': 40.0, 'color': (128, 128, 128), 'type': 'wall'}, {'x': 320.0, 'y': 440.0, 'w': 720.0, 'h': 80.0, 'color': (128, 128, 128), 'type': 'wall'}, {'x': 960.0, 'y': 640.0, 'w': 240.0, 'h': 40.0, 'color': (128, 128, 128), 'type': 'wall'}, {'x': 0.0, 'y': 40.0, 'w': 1320.0, 'h': 40.0, 'color': (50, 50, 50), 'type': 'boundary_wall_top'}, {'x': 0.0, 'y': 798.0, 'w': 1320.0, 'h': 40.0, 'color': (50, 50, 50), 'type': 'boundary_wall_bottom'}, {'x': -40.0, 'y': 40.0, 'w': 40.0, 'h': 798.0, 'color': (50, 50, 50), 'type': 'boundary_wall_left'}, {'x': 1320.0, 'y': 40.0, 'w': 40.0, 'h': 798.0, 'color': (50, 50, 50), 'type': 'boundary_wall_right'}],
        "ladders_data": [],
        "hazards_data": [{'x': 280.0, 'y': 240.0, 'w': 40.0, 'h': 41.0, 'color': (255, 0, 255), 'type': 'lava'}, {'x': 280.0, 'y': 280.0, 'w': 40.0, 'h': 41.0, 'color': (255, 0, 255), 'type': 'lava'}, {'x': 280.0, 'y': 320.0, 'w': 40.0, 'h': 41.0, 'color': (255, 0, 255), 'type': 'lava'}, {'x': 280.0, 'y': 360.0, 'w': 40.0, 'h': 41.0, 'color': (255, 0, 255), 'type': 'lava'}, {'x': 280.0, 'y': 400.0, 'w': 40.0, 'h': 41.0, 'color': (255, 0, 255), 'type': 'lava'}, {'x': 280.0, 'y': 440.0, 'w': 40.0, 'h': 41.0, 'color': (255, 0, 255), 'type': 'lava'}, {'x': 280.0, 'y': 480.0, 'w': 40.0, 'h': 41.0, 'color': (255, 0, 255), 'type': 'lava'}, {'x': 1000.0, 'y': 160.0, 'w': 40.0, 'h': 41.0, 'color': (255, 0, 255), 'type': 'lava'}, {'x': 1000.0, 'y': 200.0, 'w': 40.0, 'h': 41.0, 'color': (255, 0, 255), 'type': 'lava'}, {'x': 1000.0, 'y': 240.0, 'w': 40.0, 'h': 41.0, 'color': (255, 0, 255), 'type': 'lava'}, {'x': 1000.0, 'y': 280.0, 'w': 40.0, 'h': 41.0, 'color': (255, 0, 255), 'type': 'lava'}, {'x': 1000.0, 'y': 320.0, 'w': 40.0, 'h': 41.0, 'color': (255, 0, 255), 'type': 'lava'}, {'x': 1000.0, 'y': 360.0, 'w': 40.0, 'h': 41.0, 'color': (255, 0, 255), 'type': 'lava'}, {'x': 1000.0, 'y': 400.0, 'w': 40.0, 'h': 41.0, 'color': (255, 0, 255), 'type': 'lava'}],
        "enemy_spawns_data": [{'pos': (50.5, 758.0), 'patrol': None, 'enemy_color_id': 'yellow', 'properties': {}}, {'pos': (130.5, 758.0), 'patrol': None, 'enemy_color_id': 'red', 'properties': {}}, {'pos': (210.5, 758.0), 'patrol': None, 'enemy_color_id': 'purple', 'properties': {}}, {'pos': (290.5, 758.0), 'patrol': None, 'enemy_color_id': 'pink', 'properties': {}}, {'pos': (370.5, 718.0), 'patrol': None, 'enemy_color_id': 'green', 'properties': {}}, {'pos': (410.5, 758.0), 'patrol': None, 'enemy_color_id': 'gray', 'properties': {}}, {'pos': (450.5, 798.0), 'patrol': None, 'enemy_color_id': 'purple', 'properties': {}}, {'pos': (490.5, 798.0), 'patrol': None, 'enemy_color_id': 'purple', 'properties': {}}, {'pos': (530.5, 798.0), 'patrol': None, 'enemy_color_id': 'purple', 'properties': {}}, {'pos': (570.5, 798.0), 'patrol': None, 'enemy_color_id': 'purple', 'properties': {}}, {'pos': (610.5, 798.0), 'patrol': None, 'enemy_color_id': 'purple', 'properties': {}}, {'pos': (650.5, 798.0), 'patrol': None, 'enemy_color_id': 'purple', 'properties': {}}, {'pos': (690.5, 798.0), 'patrol': None, 'enemy_color_id': 'purple', 'properties': {}}, {'pos': (730.5, 798.0), 'patrol': None, 'enemy_color_id': 'purple', 'properties': {}}, {'pos': (770.5, 798.0), 'patrol': None, 'enemy_color_id': 'purple', 'properties': {}}, {'pos': (810.5, 798.0), 'patrol': None, 'enemy_color_id': 'purple', 'properties': {}}, {'pos': (850.5, 798.0), 'patrol': None, 'enemy_color_id': 'purple', 'properties': {}}, {'pos': (890.5, 798.0), 'patrol': None, 'enemy_color_id': 'purple', 'properties': {}}, {'pos': (930.5, 798.0), 'patrol': None, 'enemy_color_id': 'purple', 'properties': {}}, {'pos': (970.5, 798.0), 'patrol': None, 'enemy_color_id': 'purple', 'properties': {}}],
        "collectible_spawns_data": [{'type': 'chest', 'pos': (661.0, 450.0), 'properties': {}}],
        "statue_spawns_data": [],
        "dimensions_data": {'map_total_width_pixels': 1320.0, 'level_min_y_absolute': 80.0, 'level_max_y_absolute': 798.0, 'main_ground_y_reference': 798.0, 'main_ground_height_reference': 40.0}
    }
    return level_data

if __name__ == '__main__':
    # Example of how to load and print the data
    data = get_map_data_idk()
    import json
    print(json.dumps(data, indent=4))
