# Level: lavacenter2
# Generated by Platformer Level Editor
import pygame
from tiles import Platform, Ladder, Lava
from statue import Statue
import constants as C

LEVEL_SPECIFIC_BACKGROUND_COLOR = (75, 0, 130)
player1_spawn_pos = (90, 758)
player1_spawn_props = {}

def load_map_lavacenter2(initial_screen_width, initial_screen_height):
    """Loads the 'lavacenter2' level."""
    platforms = pygame.sprite.Group()
    ladders = pygame.sprite.Group()
    hazards = pygame.sprite.Group()
    enemy_spawns_data = []
    collectible_spawns_data = []
    statue_spawns_data = []

    platforms.add(Platform(0, 0, 80, 760, (128, 128, 128), platform_type='wall'))
    platforms.add(Platform(0, 760, 520, 40, (128, 128, 128), platform_type='wall'))
    platforms.add(Platform(480, 720, 40, 40, (128, 128, 128), platform_type='wall'))
    platforms.add(Platform(1000, 720, 40, 40, (128, 128, 128), platform_type='wall'))
    platforms.add(Platform(1000, 760, 200, 40, (128, 128, 128), platform_type='wall'))
    platforms.add(Platform(1120, 0, 80, 760, (128, 128, 128), platform_type='wall'))
    # No ladders placed.
    hazards.add(Lava(520, 760, 40, 41, (255, 69, 0)))
    hazards.add(Lava(560, 760, 40, 41, (255, 69, 0)))
    hazards.add(Lava(600, 760, 40, 41, (255, 69, 0)))
    hazards.add(Lava(640, 760, 40, 41, (255, 69, 0)))
    hazards.add(Lava(680, 760, 40, 41, (255, 69, 0)))
    hazards.add(Lava(720, 760, 40, 41, (255, 69, 0)))
    hazards.add(Lava(760, 760, 40, 41, (255, 69, 0)))
    hazards.add(Lava(800, 760, 40, 41, (255, 69, 0)))
    hazards.add(Lava(840, 760, 40, 41, (255, 69, 0)))
    hazards.add(Lava(880, 760, 40, 41, (255, 69, 0)))
    hazards.add(Lava(920, 760, 40, 41, (255, 69, 0)))
    hazards.add(Lava(960, 760, 40, 41, (255, 69, 0)))
    enemy_spawns_data.append({'pos': (410, 478), 'patrol': None, 'enemy_color_id': 'pink', 'properties': {}})
    collectible_spawns_data.append({'type': 'chest', 'pos': (475, 250), 'properties': {}})
    # No statue spawns defined.

    map_total_width_pixels = 1360
    level_min_y_absolute = -80
    level_max_y_absolute = 801
    main_ground_y_reference = 801
    main_ground_height_reference = 40

    _boundary_thickness = 80
    _boundary_wall_height = 1041
    _boundary_color = (50, 50, 50)

    platforms.add(Platform(1200, -160, 160, 1041, _boundary_color, platform_type='wall'))

    platforms.add(Platform(0, level_min_y_absolute - _boundary_thickness, 1360, _boundary_thickness, _boundary_color, platform_type="boundary_wall_top"))
    platforms.add(Platform(0, level_max_y_absolute, 1360, _boundary_thickness, _boundary_color, platform_type="boundary_wall_bottom"))
    platforms.add(Platform(0 - _boundary_thickness, level_min_y_absolute - _boundary_thickness, _boundary_thickness, _boundary_wall_height, _boundary_color, platform_type="boundary_wall_left"))
    platforms.add(Platform(map_total_width_pixels, level_min_y_absolute - _boundary_thickness, _boundary_thickness, _boundary_wall_height, _boundary_color, platform_type="boundary_wall_right"))

    print(f"Map 'load_map_lavacenter2' loaded with: {len(platforms)} platforms, {len(ladders)} ladders, {len(hazards)} hazards, {len(statue_spawns_data)} statues.")
    return (platforms, ladders, hazards, enemy_spawns_data, collectible_spawns_data,
            player1_spawn_pos, player1_spawn_props,
            map_total_width_pixels, level_min_y_absolute, level_max_y_absolute,
            main_ground_y_reference, main_ground_height_reference,
            LEVEL_SPECIFIC_BACKGROUND_COLOR,
            statue_spawns_data)
