# Level Data: lavacenter2
# Generated by Platformer Level Editor

# This file contains data structures that can be loaded by the game engine.
# It does not instantiate game objects directly.

def get_map_data_lavacenter2():
    level_data = {
        "map_name": 'lavacenter2',
        "background_color": (75, 0, 130),
        "player1_spawn_pos": (90.5, 758.0),
        "player1_spawn_props": {},
        "platforms_data": [{'x': 0.0, 'y': 0.0, 'w': 80.0, 'h': 760.0, 'color': (128, 128, 128), 'type': 'wall'}, {'x': 0.0, 'y': 760.0, 'w': 520.0, 'h': 40.0, 'color': (128, 128, 128), 'type': 'wall'}, {'x': 480.0, 'y': 720.0, 'w': 40.0, 'h': 40.0, 'color': (128, 128, 128), 'type': 'wall'}, {'x': 1000.0, 'y': 720.0, 'w': 40.0, 'h': 40.0, 'color': (128, 128, 128), 'type': 'wall'}, {'x': 1000.0, 'y': 760.0, 'w': 200.0, 'h': 40.0, 'color': (128, 128, 128), 'type': 'wall'}, {'x': 1120.0, 'y': 0.0, 'w': 80.0, 'h': 760.0, 'color': (128, 128, 128), 'type': 'wall'}, {'x': 0.0, 'y': -120.0, 'w': 1360.0, 'h': 40.0, 'color': (50, 50, 50), 'type': 'boundary_wall_top'}, {'x': 0.0, 'y': 801.0, 'w': 1360.0, 'h': 40.0, 'color': (50, 50, 50), 'type': 'boundary_wall_bottom'}, {'x': -40.0, 'y': -120.0, 'w': 40.0, 'h': 961.0, 'color': (50, 50, 50), 'type': 'boundary_wall_left'}, {'x': 1360.0, 'y': -120.0, 'w': 40.0, 'h': 961.0, 'color': (50, 50, 50), 'type': 'boundary_wall_right'}],
        "ladders_data": [],
        "hazards_data": [{'x': 520.0, 'y': 760.0, 'w': 480.0, 'h': 41.0, 'color': (255, 0, 255), 'type': 'lava'}],
        "enemy_spawns_data": [{'pos': (410.5, 478.0), 'patrol': None, 'enemy_color_id': 'pink', 'properties': {}}],
        "collectible_spawns_data": [{'type': 'chest', 'pos': (461.0, 250.0), 'properties': {}}],
        "statue_spawns_data": [],
        "dimensions_data": {'map_total_width_pixels': 1360.0, 'level_min_y_absolute': -80.0, 'level_max_y_absolute': 801.0, 'main_ground_y_reference': 801.0, 'main_ground_height_reference': 40.0}
    }
    return level_data

if __name__ == '__main__':
    # Example of how to load and print the data
    data = get_map_data_lavacenter2()
    import json
    print(json.dumps(data, indent=4))
