# Level Data: level_default
# Generated by Platformer Level Editor

def load_map_level_default():
    game_data = {
        'level_name': 'level_default',
        'background_color': (173, 216, 230),
        'player_start_pos_p1': (820.0, 920),
        'platforms_list': [{'rect': (-80.0, -120.0, 1760.0, 40.0), 'type': 'boundary_wall_top', 'color': (50, 50, 50), 'properties': {}}, {'rect': (-80.0, 1080.0, 1760.0, 40.0), 'type': 'boundary_wall_bottom', 'color': (50, 50, 50), 'properties': {}}, {'rect': (-120.0, -120.0, 40.0, 1240.0), 'type': 'boundary_wall_left', 'color': (50, 50, 50), 'properties': {}}, {'rect': (1680.0, -120.0, 40.0, 1240.0), 'type': 'boundary_wall_right', 'color': (50, 50, 50), 'properties': {}}],
        'ladders_list': [],
        'hazards_list': [],
        'enemies_list': [],
        'items_list': [],
        'level_pixel_width': 1760.0,
        'level_min_y_absolute': -80.0,
        'level_max_y_absolute': 1080.0,
    }
    return game_data

if __name__ == '__main__':
    data = load_map_level_default()
    import json
    print(json.dumps(data, indent=4))