# Level Data: load
# Generated by Platformer Level Editor

def load_map_load():
    game_data = {
        'level_name': 'load',
        'background_color': (173, 216, 230),
        'player_start_pos_p1': (530.5, 958.0),
        'player1_spawn_props': {'max_health': 100, 'move_speed': 350.0, 'jump_strength': -900.0},
        'player_start_pos_p2': (730.5, 958.0),
        'player2_spawn_props': {'max_health': 100, 'move_speed': 350.0, 'jump_strength': -900.0},
        'platforms_list': [{'rect': (440.0, 960.0, 400.0, 40.0), 'type': 'platform_wall_gray', 'color': (128, 128, 128), 'properties': {}}],
        'ladders_list': [],
        'hazards_list': [],
        'background_tiles_list': [],
        'enemies_list': [],
        'items_list': [],
        'statues_list': [],
        'level_pixel_width': 400.0,
        'level_min_x_absolute': 440.0,
        'level_min_y_absolute': 920.0,
        'level_max_y_absolute': 1000.0,
        'ground_level_y_ref': 960.0,
        'ground_platform_height_ref': 40.0,
    }
    return game_data

if __name__ == '__main__':
    data = load_map_load()
    import json
    print(json.dumps(data, indent=4))