# Level: long
# Generated by Platformer Level Editor
import pygame
from tiles import Platform, Ladder, Lava
from statue import Statue
import constants as C

LEVEL_SPECIFIC_BACKGROUND_COLOR = (173, 216, 230)
player1_spawn_pos = (130, 398)
player1_spawn_props = {}

def load_map_long(initial_screen_width, initial_screen_height):
    """Loads the 'long' level."""
    platforms = pygame.sprite.Group()
    ladders = pygame.sprite.Group()
    hazards = pygame.sprite.Group()
    enemy_spawns_data = []
    collectible_spawns_data = []
    statue_spawns_data = []

    platforms.add(Platform(0, 0, 120, 440, (128, 128, 128), platform_type='wall'))
    # No ladders placed.
    # No hazards placed.
    enemy_spawns_data.append({'pos': (530, 398), 'patrol': None, 'enemy_color_id': 'green', 'properties': {}})
    enemy_spawns_data.append({'pos': (1010.0, 398), 'patrol': None, 'enemy_color_id': 'green', 'properties': {}})
    enemy_spawns_data.append({'pos': (1330.0, 398), 'patrol': None, 'enemy_color_id': 'green', 'properties': {}})
    enemy_spawns_data.append({'pos': (1650.0, 398), 'patrol': None, 'enemy_color_id': 'green', 'properties': {}})
    enemy_spawns_data.append({'pos': (1930.0, 398), 'patrol': None, 'enemy_color_id': 'green', 'properties': {}})
    enemy_spawns_data.append({'pos': (2250.0, 398), 'patrol': None, 'enemy_color_id': 'green', 'properties': {}})
    enemy_spawns_data.append({'pos': (2610.0, 398), 'patrol': None, 'enemy_color_id': 'green', 'properties': {}})
    enemy_spawns_data.append({'pos': (2930.0, 398), 'patrol': None, 'enemy_color_id': 'green', 'properties': {}})
    enemy_spawns_data.append({'pos': (3290.0, 398), 'patrol': None, 'enemy_color_id': 'green', 'properties': {}})
    # No collectible spawns defined.
    # No statue spawns defined.

    map_total_width_pixels = 3461
    level_min_y_absolute = -80
    level_max_y_absolute = 440
    main_ground_y_reference = 440
    main_ground_height_reference = 40

    _boundary_thickness = 80
    _boundary_wall_height = 680
    _boundary_color = (50, 50, 50)

    platforms.add(Platform(3301, -160, 160, 680, _boundary_color, platform_type='wall'))

    platforms.add(Platform(0, level_min_y_absolute - _boundary_thickness, 3461, _boundary_thickness, _boundary_color, platform_type="boundary_wall_top"))
    platforms.add(Platform(0, level_max_y_absolute, 3461, _boundary_thickness, _boundary_color, platform_type="boundary_wall_bottom"))
    platforms.add(Platform(0 - _boundary_thickness, level_min_y_absolute - _boundary_thickness, _boundary_thickness, _boundary_wall_height, _boundary_color, platform_type="boundary_wall_left"))
    platforms.add(Platform(map_total_width_pixels, level_min_y_absolute - _boundary_thickness, _boundary_thickness, _boundary_wall_height, _boundary_color, platform_type="boundary_wall_right"))

    print(f"Map 'load_map_long' loaded with: {len(platforms)} platforms, {len(ladders)} ladders, {len(hazards)} hazards, {len(statue_spawns_data)} statues.")
    return (platforms, ladders, hazards, enemy_spawns_data, collectible_spawns_data,
            player1_spawn_pos, player1_spawn_props,
            map_total_width_pixels, level_min_y_absolute, level_max_y_absolute,
            main_ground_y_reference, main_ground_height_reference,
            LEVEL_SPECIFIC_BACKGROUND_COLOR,
            statue_spawns_data)
