# Level: long
# Generated by Platformer Level Editor (Optimized Export)
import pygame
from tiles import Platform, Ladder, Lava
import constants as C

LEVEL_SPECIFIC_BACKGROUND_COLOR = (173, 216, 230)

def load_map_long(initial_screen_width, initial_screen_height):
    """
    Loads the 'long' level.
    """
    print(f"Loading map: load_map_long...")
    platforms = pygame.sprite.Group()
    ladders = pygame.sprite.Group()
    hazards = pygame.sprite.Group()
    enemy_spawns_data = []
    collectible_spawns_data = []

    player1_spawn = (129, 397)

    # --- Placed Objects (merged where possible) ---
    platforms.add(Platform(0, 0, 120, 440, (128,128,128), platform_type='wall'))
    # No ladders placed.
    # No hazards placed.
    enemy_spawns_data.append({'pos': (529, 397), 'patrol': None, 'enemy_color_id': 'green'})
    enemy_spawns_data.append({'pos': (1009.0, 397), 'patrol': None, 'enemy_color_id': 'green'})
    enemy_spawns_data.append({'pos': (1329.0, 397), 'patrol': None, 'enemy_color_id': 'green'})
    enemy_spawns_data.append({'pos': (1649.0, 397), 'patrol': None, 'enemy_color_id': 'green'})
    enemy_spawns_data.append({'pos': (1929.0, 397), 'patrol': None, 'enemy_color_id': 'green'})
    enemy_spawns_data.append({'pos': (2249.0, 397), 'patrol': None, 'enemy_color_id': 'green'})
    enemy_spawns_data.append({'pos': (2609.0, 397), 'patrol': None, 'enemy_color_id': 'green'})
    enemy_spawns_data.append({'pos': (2929.0, 397), 'patrol': None, 'enemy_color_id': 'green'})
    enemy_spawns_data.append({'pos': (3289.0, 397), 'patrol': None, 'enemy_color_id': 'green'})
    # No collectible spawns defined.

    # --- Level Dimensions for Game Camera & Boundaries ---
    map_total_width_pixels = 3459
    level_min_y_absolute = -80
    level_max_y_absolute = 440
    main_ground_y_reference = 440
    main_ground_height_reference = 40

    _boundary_thickness = C.TILE_SIZE * 2
    _boundary_wall_height = level_max_y_absolute - level_min_y_absolute + (2 * _boundary_thickness)
    _boundary_color = getattr(C, 'DARK_GRAY', (50,50,50))

    # Filler wall on the right to ensure no empty background padding
    platforms.add(Platform(3299, level_min_y_absolute - _boundary_thickness, 160, _boundary_wall_height, _boundary_color, platform_type='wall'))

    # Boundary platforms (these define the absolute edges of the level area)
    # Top boundary (ceiling)
    platforms.add(Platform(0, level_min_y_absolute - _boundary_thickness, map_total_width_pixels, _boundary_thickness, _boundary_color, platform_type="boundary_wall_top"))
    # Bottom boundary (floor/kill plane)
    platforms.add(Platform(0, level_max_y_absolute, map_total_width_pixels, _boundary_thickness, _boundary_color, platform_type="boundary_wall_bottom"))
    # Left boundary
    platforms.add(Platform(-_boundary_thickness, level_min_y_absolute - _boundary_thickness, _boundary_thickness, _boundary_wall_height, _boundary_color, platform_type="boundary_wall_left"))
    # Right boundary (placed at the very edge of map_total_width_pixels)
    platforms.add(Platform(map_total_width_pixels, level_min_y_absolute - _boundary_thickness, _boundary_thickness, _boundary_wall_height, _boundary_color, platform_type="boundary_wall_right"))

    print(f"Map 'load_map_long' loaded with: {len(platforms)} platforms, {len(ladders)} ladders, {len(hazards)} hazards.")
    return (platforms, ladders, hazards, enemy_spawns_data, collectible_spawns_data,
            player1_spawn,
            map_total_width_pixels, level_min_y_absolute, level_max_y_absolute,
            main_ground_y_reference, main_ground_height_reference,
            LEVEL_SPECIFIC_BACKGROUND_COLOR)