# Level Data: one
# Generated by Platformer Level Editor

def load_map_one():
    game_data = {
        'level_name': 'one',
        'background_color': (173, 216, 230),
        'player_start_pos_p1': (610.5, 838.0),
        'platforms_list': [{'rect': (440.0, 840.0, 80.0, 40.0), 'type': 'platform_wall_gray', 'color': (128, 128, 128), 'properties': {}}, {'rect': (480.0, 880.0, 440.0, 40.0), 'type': 'platform_wall_gray', 'color': (128, 128, 128), 'properties': {}}, {'rect': (880.0, 840.0, 80.0, 40.0), 'type': 'platform_wall_gray', 'color': (128, 128, 128), 'properties': {}}, {'rect': (920.0, 800.0, 40.0, 40.0), 'type': 'platform_wall_gray', 'color': (128, 128, 128), 'properties': {}}, {'rect': (360.0, 680.0, 680.0, 40.0), 'type': 'boundary_wall_top', 'color': (50, 50, 50), 'properties': {}}, {'rect': (360.0, 1000.0, 680.0, 40.0), 'type': 'boundary_wall_bottom', 'color': (50, 50, 50), 'properties': {}}, {'rect': (320.0, 680.0, 40.0, 360.0), 'type': 'boundary_wall_left', 'color': (50, 50, 50), 'properties': {}}, {'rect': (1040.0, 680.0, 40.0, 360.0), 'type': 'boundary_wall_right', 'color': (50, 50, 50), 'properties': {}}],
        'ladders_list': [],
        'hazards_list': [],
        'enemies_list': [],
        'items_list': [],
        'level_pixel_width': 1040.0,
        'level_min_y_absolute': 720.0,
        'level_max_y_absolute': 1000.0,
        'player_start_pos_p2': (770.5, 838.0),
    }
    return game_data

if __name__ == '__main__':
    data = load_map_one()
    import json
    print(json.dumps(data, indent=4))