# Level Data: test
# Generated by Platformer Level Editor

def load_map_test():
    game_data = {
        'level_name': 'test',
        'background_color': (173, 216, 230),
        'player_start_pos_p1': (1210.5, 638.0),
        'player1_spawn_props': {'max_health': 100, 'move_speed': 350.0, 'jump_strength': -900.0},
        'player_start_pos_p2': (1330.5, 638.0),
        'player2_spawn_props': {'max_health': 100, 'move_speed': 350.0, 'jump_strength': -900.0},
        'platforms_list': [{'rect': (0.0, 80.0, 80.0, 840.0), 'type': 'platform_wall_gray', 'color': (128, 128, 128), 'properties': {'is_boundary': True}}, {'rect': (0.0, 0.0, 1600.0, 80.0), 'type': 'platform_wall_gray', 'color': (128, 128, 128), 'properties': {'is_boundary': True}}, {'rect': (0.0, 920.0, 1600.0, 80.0), 'type': 'platform_wall_gray', 'color': (128, 128, 128), 'properties': {'is_boundary': True}}, {'rect': (1520.0, 80.0, 80.0, 840.0), 'type': 'platform_wall_gray', 'color': (128, 128, 128), 'properties': {'is_boundary': True}}],
        'ladders_list': [],
        'hazards_list': [],
        'background_tiles_list': [],
        'enemies_list': [{'start_pos': (210.5, 878.0), 'type': 'enemy_green', 'properties': {'patrol_range_tiles': 6, 'move_speed': 100.0, 'health': 4, 'can_fly': False}}, {'start_pos': (250.5, 878.0), 'type': 'enemy_green', 'properties': {'patrol_range_tiles': 6, 'move_speed': 100.0, 'health': 4, 'can_fly': False}}, {'start_pos': (290.5, 878.0), 'type': 'enemy_green', 'properties': {'patrol_range_tiles': 6, 'move_speed': 100.0, 'health': 4, 'can_fly': False}}, {'start_pos': (330.5, 878.0), 'type': 'enemy_green', 'properties': {'patrol_range_tiles': 6, 'move_speed': 100.0, 'health': 4, 'can_fly': False}}, {'start_pos': (370.5, 878.0), 'type': 'enemy_green', 'properties': {'patrol_range_tiles': 6, 'move_speed': 100.0, 'health': 4, 'can_fly': False}}, {'start_pos': (410.5, 878.0), 'type': 'enemy_green', 'properties': {'patrol_range_tiles': 6, 'move_speed': 100.0, 'health': 4, 'can_fly': False}}, {'start_pos': (450.5, 878.0), 'type': 'enemy_green', 'properties': {'patrol_range_tiles': 6, 'move_speed': 100.0, 'health': 4, 'can_fly': False}}, {'start_pos': (490.5, 878.0), 'type': 'enemy_green', 'properties': {'patrol_range_tiles': 6, 'move_speed': 100.0, 'health': 4, 'can_fly': False}}],
        'items_list': [],
        'statues_list': [],
        'level_pixel_width': 1600.0,
        'level_min_x_absolute': 0.0,
        'level_min_y_absolute': 0.0,
        'level_max_y_absolute': 1000.0,
        'ground_level_y_ref': 920.0,
        'ground_platform_height_ref': 80.0,
    }
    return game_data

if __name__ == '__main__':
    data = load_map_test()
    import json
    print(json.dumps(data, indent=4))