# Level: test1
# Generated by Platformer Level Editor (PySide6 Version - Optimized Export)
import pygame
from tiles import Platform, Ladder, Lava # Make sure these match your game's tile classes
import constants as C

LEVEL_SPECIFIC_BACKGROUND_COLOR = (173, 216, 230)
player1_spawn_pos = (570, 558)
player1_spawn_props = {'max_health': 100, 'move_speed': 300.0, 'jump_strength': -900.0}

def load_map_test1(initial_screen_width, initial_screen_height):
    """Loads the 'test1' level."""
    print(f"Loading map: load_map_test1...")
    platforms = pygame.sprite.Group()
    ladders = pygame.sprite.Group()
    hazards = pygame.sprite.Group()
    enemy_spawns_data = []
    collectible_spawns_data = []

    # --- Placed Objects (merged where possible) ---
    platforms.add(Platform(160, 160, 240, 40, (170, 0, 0), platform_type='wall'))
    platforms.add(Platform(360, 120, 80, 40, (170, 0, 0), platform_type='wall'))
    platforms.add(Platform(160, 200, 40, 40, (85, 170, 255), platform_type='wall'))
    platforms.add(Platform(160, 240, 80, 40, (85, 170, 255), platform_type='wall'))
    platforms.add(Platform(200, 280, 280, 40, (85, 170, 255), platform_type='wall'))
    platforms.add(Platform(280, 520, 160, 40, (85, 170, 255), platform_type='wall'))
    platforms.add(Platform(320, 320, 80, 40, (85, 170, 255), platform_type='wall'))
    platforms.add(Platform(400, 560, 320, 40, (85, 170, 255), platform_type='wall'))
    platforms.add(Platform(440, 240, 80, 40, (85, 170, 255), platform_type='wall'))
    platforms.add(Platform(680, 520, 280, 40, (85, 170, 255), platform_type='wall'))
    platforms.add(Platform(720, 240, 40, 120, (85, 170, 255), platform_type='wall'))
    platforms.add(Platform(720, 360, 80, 40, (85, 170, 255), platform_type='wall'))
    platforms.add(Platform(760, 400, 200, 40, (85, 170, 255), platform_type='wall'))
    platforms.add(Platform(920, 280, 120, 40, (85, 170, 255), platform_type='wall'))
    platforms.add(Platform(960, 360, 120, 40, (85, 170, 255), platform_type='wall'))
    platforms.add(Platform(960, 600, 120, 40, (85, 170, 255), platform_type='wall'))
    platforms.add(Platform(1000, 320, 40, 40, (85, 170, 255), platform_type='wall'))
    platforms.add(Platform(1040, 400, 80, 40, (85, 170, 255), platform_type='wall'))
    platforms.add(Platform(1080, 520, 200, 40, (85, 170, 255), platform_type='wall'))
    platforms.add(Platform(1200, 400, 120, 40, (85, 170, 255), platform_type='wall'))
    # No ladders placed.
    # No hazards placed.
    enemy_spawns_data.append({'pos': (770, 358), 'patrol': None, 'enemy_color_id': 'purple', 'properties': {'health': 5, 'attack_damage': 2, 'can_fly': True}})
    collectible_spawns_data.append({'type': 'chest', 'pos': (355, 530), 'properties': {'item_type': 'coin', 'item_quantity': 1}})

    # --- Level Dimensions for Game Camera & Boundaries ---
    map_total_width_pixels = 1400
    level_min_y_absolute = 40
    level_max_y_absolute = 640
    main_ground_y_reference = 640
    main_ground_height_reference = 40

    _boundary_thickness = C.TILE_SIZE * 2
    _boundary_wall_height = level_max_y_absolute - level_min_y_absolute + (2 * _boundary_thickness)
    # Ensure height is positive if level_min_y_absolute is very large (e.g. map is high up)
    _boundary_wall_height = max(_boundary_thickness * 2, _boundary_wall_height)


    _boundary_color = getattr(C, 'DARK_GRAY', (50,50,50))

    # Filler wall on the far right (if map_total_width_pixels extends beyond content)
    platforms.add(Platform(1320, level_min_y_absolute - _boundary_thickness, 80, _boundary_wall_height, _boundary_color, platform_type='wall'))

    # Boundary platforms (ensure these use effective_min_x_for_bounds if map doesn't start at 0)
    platforms.add(Platform(0, level_min_y_absolute - _boundary_thickness, map_total_width_pixels - effective_min_x_for_bounds, _boundary_thickness, _boundary_color, platform_type="boundary_wall_top"))
    platforms.add(Platform(0, level_max_y_absolute, map_total_width_pixels - effective_min_x_for_bounds, _boundary_thickness, _boundary_color, platform_type="boundary_wall_bottom"))
    platforms.add(Platform(effective_min_x_for_bounds - _boundary_thickness, level_min_y_absolute - _boundary_thickness, _boundary_thickness, _boundary_wall_height, _boundary_color, platform_type="boundary_wall_left"))
    platforms.add(Platform(map_total_width_pixels, level_min_y_absolute - _boundary_thickness, _boundary_thickness, _boundary_wall_height, _boundary_color, platform_type="boundary_wall_right"))

    print(f"Map '{function_name}' loaded with: {len(platforms)} platforms, {len(ladders)} ladders, {len(hazards)} hazards.")
    return (platforms, ladders, hazards, enemy_spawns_data, collectible_spawns_data,
            player1_spawn_pos, player1_spawn_props, # Ensure these are the global vars from the file
            map_total_width_pixels, level_min_y_absolute, level_max_y_absolute,
            main_ground_y_reference, main_ground_height_reference,
            LEVEL_SPECIFIC_BACKGROUND_COLOR)
