# Level Data: three
# Generated by Platformer Level Editor

def load_map_three():
    game_data = {
        'level_name': 'three',
        'background_color': (173, 216, 230),
        'player_start_pos_p1': (210.5, 918.0),
        'player1_spawn_props': {'max_health': 100, 'move_speed': 350.0, 'jump_strength': -900.0},
        'player_start_pos_p2': (130.5, 918.0),
        'player2_spawn_props': {'max_health': 100, 'move_speed': 350.0, 'jump_strength': -900.0},
        'platforms_list': [{'rect': (320.0, 800.0, 80.0, 13.0), 'type': 'platform_ledge_green_one_third', 'color': (0, 100, 0), 'properties': {}}, {'rect': (360.0, 720.0, 80.0, 13.0), 'type': 'platform_ledge_green_one_third', 'color': (0, 100, 0), 'properties': {}}, {'rect': (0.0, 80.0, 80.0, 600.0), 'type': 'platform_wall_gray', 'color': (128, 128, 128), 'properties': {'is_boundary': True}}, {'rect': (0.0, 720.0, 80.0, 200.0), 'type': 'platform_wall_gray', 'color': (128, 128, 128), 'properties': {'is_boundary': True}}, {'rect': (0.0, 680.0, 280.0, 40.0), 'type': 'platform_wall_gray', 'color': (128, 128, 128), 'properties': {'is_boundary': True}}, {'rect': (0.0, 0.0, 1600.0, 80.0), 'type': 'platform_wall_gray', 'color': (128, 128, 128), 'properties': {'is_boundary': True}}, {'rect': (0.0, 920.0, 1600.0, 80.0), 'type': 'platform_wall_gray', 'color': (128, 128, 128), 'properties': {'is_boundary': True}}, {'rect': (160.0, 640.0, 40.0, 40.0), 'type': 'platform_wall_gray', 'color': (128, 128, 128), 'properties': {}}, {'rect': (280.0, 880.0, 40.0, 40.0), 'type': 'platform_wall_gray', 'color': (128, 128, 128), 'properties': {}}, {'rect': (520.0, 880.0, 40.0, 40.0), 'type': 'platform_wall_gray', 'color': (128, 128, 128), 'properties': {}}, {'rect': (1520.0, 80.0, 80.0, 840.0), 'type': 'platform_wall_gray', 'color': (128, 128, 128), 'properties': {'is_boundary': True}}],
        'ladders_list': [],
        'hazards_list': [{'rect': (320.0, 880.0, 200.0, 42.0), 'type': 'hazard_lava', 'color': (255, 69, 0), 'properties': {}}],
        'background_tiles_list': [],
        'enemies_list': [{'start_pos': (610.5, 878.0), 'type': 'enemy_gray', 'properties': {'health': 3, 'move_speed': 150.0}}, {'start_pos': (610.5, 918.0), 'type': 'enemy_gray', 'properties': {'health': 3, 'move_speed': 150.0}}, {'start_pos': (650.5, 878.0), 'type': 'enemy_gray', 'properties': {'health': 3, 'move_speed': 150.0}}, {'start_pos': (650.5, 918.0), 'type': 'enemy_gray', 'properties': {'health': 3, 'move_speed': 150.0}}, {'start_pos': (690.5, 918.0), 'type': 'enemy_gray', 'properties': {'health': 3, 'move_speed': 150.0}}],
        'items_list': [{'type': 'chest', 'pos': (181.0, 625.0), 'properties': {'item_type': 'coin', 'item_quantity': 1}}],
        'statues_list': [],
        'level_pixel_width': 1600.0,
        'level_min_x_absolute': 0.0,
        'level_min_y_absolute': 0.0,
        'level_max_y_absolute': 1000.0,
        'ground_level_y_ref': 920.0,
        'ground_platform_height_ref': 80.0,
    }
    return game_data

if __name__ == '__main__':
    data = load_map_three()
    import json
    print(json.dumps(data, indent=4))