# Level Data: ttt
# Generated by Platformer Level Editor

def load_map_ttt():
    game_data = {
        'level_name': 'ttt',
        'background_color': (173, 216, 230),
        'player_start_pos_p1': (610.5, 238.0),
        'platforms_list': [{'rect': (120.0, 160.0, 40.0, 40.0), 'type': 'platform_ledge_green', 'color': (0, 100, 0), 'properties': {}}, {'rect': (120.0, 240.0, 40.0, 40.0), 'type': 'platform_ledge_green', 'color': (0, 100, 0), 'properties': {}}, {'rect': (240.0, 240.0, 440.0, 40.0), 'type': 'platform_ledge_green', 'color': (0, 100, 0), 'properties': {}}, {'rect': (440.0, 440.0, 200.0, 40.0), 'type': 'platform_ledge_green', 'color': (0, 100, 0), 'properties': {}}, {'rect': (560.0, 320.0, 40.0, 40.0), 'type': 'platform_ledge_green', 'color': (0, 100, 0), 'properties': {}}, {'rect': (40.0, 40.0, 720.0, 40.0), 'color': (50, 50, 50), 'type': 'boundary_wall_top', 'properties': {}}, {'rect': (40.0, 520.0, 720.0, 40.0), 'color': (50, 50, 50), 'type': 'boundary_wall_bottom', 'properties': {}}, {'rect': (40.0, 80.0, 40.0, 440.0), 'color': (50, 50, 50), 'type': 'boundary_wall_left', 'properties': {}}, {'rect': (720.0, 80.0, 40.0, 440.0), 'color': (50, 50, 50), 'type': 'boundary_wall_right', 'properties': {}}],
        'ladders_list': [],
        'hazards_list': [],
        'enemies_list': [],
        'items_list': [{'type': 'chest', 'pos': (221.0, 225.0), 'properties': {'item_type': 'coin', 'item_quantity': 1}}],
        'statues_list': [{'id': 'statue_0', 'pos': (416.5, 218.0), 'properties': {'destructible': False, 'hardness': 1}}, {'id': 'statue_1', 'pos': (416.5, 138.0), 'properties': {'destructible': False, 'hardness': 1}}, {'id': 'statue_2', 'pos': (456.5, 178.0), 'properties': {'destructible': False, 'hardness': 1}}, {'id': 'statue_3', 'pos': (496.5, 138.0), 'properties': {'destructible': False, 'hardness': 1}}, {'id': 'statue_4', 'pos': (536.5, 178.0), 'properties': {'destructible': False, 'hardness': 1}}],
        'level_pixel_width': 720.0,
        'level_min_x_absolute': 40.0,
        'level_min_y_absolute': 40.0,
        'level_max_y_absolute': 560.0,
        'ground_level_y_ref': 440.0,
        'ground_platform_height_ref': 40.0,
        'player_start_pos_p2': (530.5, 438.0),
    }
    return game_data

if __name__ == '__main__':
    data = load_map_ttt()
    import json
    print(json.dumps(data, indent=4))