# Level: ttt
# Generated by Platformer Level Editor
import pygame
from tiles import Platform, Ladder, Lava
from statue import Statue
import constants as C

LEVEL_SPECIFIC_BACKGROUND_COLOR = (173, 216, 230)
player1_spawn_pos = (610, 238)
player1_spawn_props = {'max_health': 100, 'move_speed': 300.0, 'jump_strength': -900.0}

def load_map_ttt(initial_screen_width, initial_screen_height):
    """Loads the 'ttt' level."""
    platforms = pygame.sprite.Group()
    ladders = pygame.sprite.Group()
    hazards = pygame.sprite.Group()
    enemy_spawns_data = []
    collectible_spawns_data = []
    statue_spawns_data = []

    platforms.add(Platform(120, 160, 40, 40, (0, 100, 0), platform_type='ledge'))
    platforms.add(Platform(120, 240, 40, 40, (0, 100, 0), platform_type='ledge'))
    platforms.add(Platform(240, 240, 440, 40, (0, 100, 0), platform_type='ledge'))
    platforms.add(Platform(440, 440, 200, 40, (0, 100, 0), platform_type='ledge'))
    platforms.add(Platform(560, 320, 40, 40, (0, 100, 0), platform_type='ledge'))
    # No ladders placed.
    # No hazards placed.
    # No enemy spawns defined.
    collectible_spawns_data.append({'type': 'chest', 'pos': (235, 250), 'properties': {'item_type': 'coin', 'item_quantity': 1}})
    statue_spawns_data.append({'id': 'object_stone_idle_400_200', 'pos': (416.5, 218.0), 'properties': {'destructible': False, 'hardness': 1}})
    statue_spawns_data.append({'id': 'object_stone_idle_400_120', 'pos': (416.5, 138.0), 'properties': {'destructible': False, 'hardness': 1}})
    statue_spawns_data.append({'id': 'object_stone_idle_440_160', 'pos': (456.5, 178.0), 'properties': {'destructible': False, 'hardness': 1}})
    statue_spawns_data.append({'id': 'object_stone_idle_480_120', 'pos': (496.5, 138.0), 'properties': {'destructible': False, 'hardness': 1}})
    statue_spawns_data.append({'id': 'object_stone_idle_520_160', 'pos': (536.5, 178.0), 'properties': {'destructible': False, 'hardness': 1}})

    map_total_width_pixels = 1000
    level_min_y_absolute = 40
    level_max_y_absolute = 480
    main_ground_y_reference = 480
    main_ground_height_reference = 40

    _boundary_thickness = 80
    _boundary_wall_height = 600
    _boundary_color = (50, 50, 50)

    platforms.add(Platform(680, -40, 320, 600, _boundary_color, platform_type='wall'))

    platforms.add(Platform(0, level_min_y_absolute - _boundary_thickness, 1000, _boundary_thickness, _boundary_color, platform_type="boundary_wall_top"))
    platforms.add(Platform(0, level_max_y_absolute, 1000, _boundary_thickness, _boundary_color, platform_type="boundary_wall_bottom"))
    platforms.add(Platform(0 - _boundary_thickness, level_min_y_absolute - _boundary_thickness, _boundary_thickness, _boundary_wall_height, _boundary_color, platform_type="boundary_wall_left"))
    platforms.add(Platform(map_total_width_pixels, level_min_y_absolute - _boundary_thickness, _boundary_thickness, _boundary_wall_height, _boundary_color, platform_type="boundary_wall_right"))

    print(f"Map 'load_map_ttt' loaded with: {len(platforms)} platforms, {len(ladders)} ladders, {len(hazards)} hazards, {len(statue_spawns_data)} statues.")
    return (platforms, ladders, hazards, enemy_spawns_data, collectible_spawns_data,
            player1_spawn_pos, player1_spawn_props,
            map_total_width_pixels, level_min_y_absolute, level_max_y_absolute,
            main_ground_y_reference, main_ground_height_reference,
            LEVEL_SPECIFIC_BACKGROUND_COLOR,
            statue_spawns_data)
