# Level Data: two
# Generated by Platformer Level Editor

def load_map_two():
    game_data = {
        'level_name': 'two',
        'background_color': (173, 216, 230),
        'player_start_pos_p1': (50.5, 998.0),
        'player1_spawn_props': {'max_health': 100, 'move_speed': 350.0, 'jump_strength': -900.0},
        'player_start_pos_p2': (90.5, 838.0),
        'player2_spawn_props': {'max_health': 100, 'move_speed': 350.0, 'jump_strength': -900.0},
        'platforms_list': [{'rect': (160.0, 960.0, 40.0, 10.0), 'type': 'platform_ledge_gray_one_fourth', 'color': (128, 128, 128), 'properties': {}}, {'rect': (0.0, 840.0, 200.0, 40.0), 'type': 'platform_wall_gray', 'color': (128, 128, 128), 'properties': {}}, {'rect': (160.0, 880.0, 40.0, 80.0), 'type': 'platform_wall_gray', 'color': (128, 128, 128), 'properties': {}}, {'rect': (320.0, 960.0, 80.0, 40.0), 'type': 'platform_wall_gray', 'color': (128, 128, 128), 'properties': {}}, {'rect': (360.0, 880.0, 40.0, 80.0), 'type': 'platform_wall_gray', 'color': (128, 128, 128), 'properties': {}}, {'rect': (720.0, 960.0, 120.0, 40.0), 'type': 'platform_wall_gray', 'color': (128, 128, 128), 'properties': {}}, {'rect': (760.0, 920.0, 40.0, 40.0), 'type': 'platform_wall_gray', 'color': (128, 128, 128), 'properties': {}}],
        'ladders_list': [],
        'hazards_list': [{'rect': (840.0, 960.0, 320.0, 42.0), 'type': 'hazard_lava', 'color': (255, 69, 0), 'properties': {}}],
        'background_tiles_list': [],
        'enemies_list': [{'start_pos': (450.5, 998.0), 'type': 'enemy_gray', 'properties': {'health': 3, 'move_speed': 150.0}}, {'start_pos': (610.5, 998.0), 'type': 'enemy_green', 'properties': {'patrol_range_tiles': 6, 'move_speed': 100.0, 'health': 4, 'can_fly': False}}],
        'items_list': [{'type': 'chest', 'pos': (781.0, 905.0), 'properties': {'item_type': 'coin', 'item_quantity': 1}}],
        'statues_list': [],
        'level_pixel_width': 1160.0,
        'level_min_x_absolute': 0.0,
        'level_min_y_absolute': 800.0,
        'level_max_y_absolute': 1002.0,
        'ground_level_y_ref': 960.0,
        'ground_platform_height_ref': 40.0,
    }
    return game_data

if __name__ == '__main__':
    data = load_map_two()
    import json
    print(json.dumps(data, indent=4))