# Level Data: testdel
# Generated by Platformer Level Editor

def load_map_testdel():
    game_data = {
        'level_name': 'testdel',
        'background_color': (173, 216, 230),
        'player_start_pos_p1': (170.5, 198.0),
        'player1_spawn_props': {'max_health': 100, 'move_speed': 350.0, 'jump_strength': -900.0, 'is_flipped_h': False},
        'platforms_list': [{'rect': (160.0, 200.0, 40.0, 40.0), 'type': 'platform_wall_gray', 'color': (128, 128, 128), 'properties': {'destructible': False, 'health': 100, 'material_type': 'stone', 'corner_radius': 20, 'round_top_left': True, 'round_top_right': True, 'round_bottom_left': True, 'round_bottom_right': True}, 'is_flipped_h': False}],
        'ladders_list': [],
        'hazards_list': [],
        'background_tiles_list': [],
        'enemies_list': [],
        'items_list': [],
        'statues_list': [],
        'custom_images_list': [],
        'trigger_squares_list': [],
        'level_pixel_width': 40.0,
        'level_min_x_absolute': 160.0,
        'level_min_y_absolute': 160.0,
        'level_max_y_absolute': 240.0,
        'ground_level_y_ref': 240.0,
        'ground_platform_height_ref': 40.0,
    }
    return game_data

if __name__ == '__main__':
    data = load_map_testdel()
    import json
    print(json.dumps(data, indent=4))