# Level Data: three
# Generated by Platformer Level Editor

def load_map_three():
    game_data = {
        'level_name': 'three',
        'background_color': (173, 216, 230),
        'player_start_pos_p1': (210.5, 918.0),
        'player1_spawn_props': {'max_health': 100, 'move_speed': 350.0, 'jump_strength': -900.0},
        'platforms_list': [{'rect': (320.0, 800.0, 80.0, 40.0), 'type': 'platform_ledge_green_one_third', 'color': (128, 128, 128), 'properties': {}}, {'rect': (360.0, 720.0, 80.0, 40.0), 'type': 'platform_ledge_green_one_third', 'color': (128, 128, 128), 'properties': {}}, {'rect': (0.0, 80.0, 80, 600), 'type': 'platform_wall_gray', 'color': (128, 128, 128), 'properties': {'is_boundary': True}}, {'rect': (0.0, 720.0, 80, 200), 'type': 'platform_wall_gray', 'color': (128, 128, 128), 'properties': {'is_boundary': True}}, {'rect': (0.0, 680.0, 280, 40), 'type': 'platform_wall_gray', 'color': (128, 128, 128), 'properties': {'is_boundary': True}}, {'rect': (0.0, 0.0, 1600, 80), 'type': 'platform_wall_gray', 'color': (128, 128, 128), 'properties': {'is_boundary': True}}, {'rect': (0.0, 920.0, 1600, 80), 'type': 'platform_wall_gray', 'color': (128, 128, 128), 'properties': {'is_boundary': True}}, {'rect': (160.0, 640.0, 40, 40), 'type': 'platform_wall_gray', 'color': (128, 128, 128), 'properties': {}}, {'rect': (280.0, 880.0, 40, 40), 'type': 'platform_wall_gray', 'color': (128, 128, 128), 'properties': {}}, {'rect': (520.0, 880.0, 40, 40), 'type': 'platform_wall_gray', 'color': (128, 128, 128), 'properties': {}}, {'rect': (760.0, 800.0, 40, 120), 'type': 'platform_wall_gray', 'color': (128, 128, 128), 'properties': {}}, {'rect': (1520.0, 80.0, 80, 840), 'type': 'platform_wall_gray', 'color': (128, 128, 128), 'properties': {'is_boundary': True}}, {'rect': (960.0, 760.0, 40, 160), 'type': 'platform_wall_gray', 'color': (85, 170, 0), 'properties': {}}],
        'ladders_list': [],
        'hazards_list': [{'rect': (320.0, 880.0, 200, 42), 'type': 'hazard_lava', 'color': (128, 128, 128), 'properties': {}}],
        'background_tiles_list': [],
        'enemies_list': [{'start_pos': (610.5, 918.0), 'type': 'enemy_gray', 'properties': {'health': 3, 'move_speed': 150.0}}, {'start_pos': (650.5, 918.0), 'type': 'enemy_gray', 'properties': {'health': 3, 'move_speed': 150.0}}, {'start_pos': (690.5, 918.0), 'type': 'enemy_gray', 'properties': {'health': 3, 'move_speed': 150.0}}, {'start_pos': (850.5, 918.0), 'type': 'enemy_pink', 'properties': {'health': 2, 'move_speed': 120.0, 'patrol_behavior': 'turn_on_edge'}}, {'start_pos': (1050.5, 918.0), 'type': 'enemy_green', 'properties': {'patrol_range_tiles': 6, 'move_speed': 100.0, 'health': 4, 'can_fly': False}}],
        'items_list': [{'pos': (181.0, 625.0), 'type': 'chest', 'properties': {'item_type': 'coin', 'item_quantity': 1}}],
        'statues_list': [],
        'custom_images_list': [{'rect': (8.0, 22.0, 1733.0, 975.0), 'source_file_path': 'Custom/R-C.jpg', 'layer_order': -2, 'properties': {'is_background': True, 'is_obstacle': False, 'destructible': False, 'health': 99}}],
        'trigger_squares_list': [],
        'level_pixel_width': 1741.0,
        'level_min_x_absolute': 0.0,
        'level_min_y_absolute': 0.0,
        'level_max_y_absolute': 1000.0,
        'ground_level_y_ref': 1000.0,
        'ground_platform_height_ref': 40.0,
    }
    return game_data

if __name__ == '__main__':
    data = load_map_three()
    import json
    print(json.dumps(data, indent=4))