# .github/workflows/main.yaml
name: Build Windows Executable (Platformer Game)

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  release:
    types: [published]

jobs:
  build-windows:
    name: Build Platformer for Windows
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt 
          # PySide6 is in requirements.txt, no need to install separately here
          # Pillow is in requirements.txt
          # pygame is in requirements.txt
        shell: pwsh

      # --- Build Platformer.exe ---
      - name: Generate Base PyInstaller Spec File for Platformer
        run: |
          pyi-makespec --windowed --name Platformer `
            --hidden-import PIL `
            --hidden-import PIL.Image `
            --hidden-import numpy `
            --hidden-import PySide6.QtGui `
            --hidden-import PySide6.QtCore `
            --hidden-import PySide6.QtWidgets `
            --hidden-import pygame `
            main.py
        shell: pwsh

      - name: Modify the Spec File to Add Data Files for Platformer
        run: |
          $specFile = "Platformer.spec"
          Write-Host "Checking if $specFile exists..."
          if (!(Test-Path $specFile)) {
            Write-Error "$specFile not found after pyi-makespec!"
            exit 1
          }
          Write-Host "$specFile found. Attempting to modify..."
          $specContent = Get-Content -Path $specFile -Raw
          
          # Add 'characters', 'maps', and 'controller_settings' folders.
          # The paths are relative to the project root (where main.py and the spec file are).
          # The destination is relative to the bundled app's root (dist/Platformer/).
          $dataToAdd = "[('characters', 'characters'), ('maps', 'maps'), ('controller_settings', 'controller_settings')]"
                                        
          $modifiedContent = $specContent -replace 'datas=\s*\[\s*\]', "datas=$dataToAdd"

          if ($specContent -eq $modifiedContent) {
            Write-Host "--- Platformer Spec File Content START ---"
            Write-Host $specContent
            Write-Host "--- Platformer Spec File Content END ---"
            Write-Error "Failed to find and replace 'datas=[]' pattern in $specFile. Check the spec file content."
            exit 1
          }

          Set-Content -Path $specFile -Value $modifiedContent
          Write-Host "Successfully added datas to $specFile."
          Write-Host "--- Modified Platformer Spec File Content START ---"
          Get-Content -Path $specFile | Write-Host
          Write-Host "--- Modified Platformer Spec File Content END ---"
        shell: pwsh

      - name: Build Platformer executable from Spec File
        run: |
          pyinstaller --noconfirm --log-level INFO Platformer.spec
        shell: pwsh

      - name: Upload Platformer Windows Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Platformer-Windows-Release
          path: dist/Platformer/
          if-no-files-found: error