# Level Data: two_2
# Generated by Platformer Level Editor

def load_map_two_2():
    game_data = {
        'level_name': 'two_2',
        'background_color': (173, 216, 230),
        'player_start_pos_p1': (90.5, 918.0),
        'player1_spawn_props': {'max_health': 100, 'move_speed': 350.0, 'jump_strength': -900.0},
        'platforms_list': [{'rect': (0.0, 40.0, 40, 920), 'type': 'platform_wall_gray', 'color': (128, 128, 128), 'properties': {'is_boundary': True}}, {'rect': (0.0, 0.0, 1600, 40), 'type': 'platform_wall_gray', 'color': (128, 128, 128), 'properties': {'is_boundary': True}}, {'rect': (0.0, 960.0, 1600, 40), 'type': 'platform_wall_gray', 'color': (128, 128, 128), 'properties': {'is_boundary': True}}, {'rect': (1560.0, 40.0, 40, 920), 'type': 'platform_wall_gray', 'color': (128, 128, 128), 'properties': {'is_boundary': True}}],
        'ladders_list': [],
        'hazards_list': [],
        'background_tiles_list': [],
        'enemies_list': [],
        'items_list': [],
        'statues_list': [],
        'custom_images_list': [],
        'trigger_squares_list': [],
        'level_pixel_width': 1600.0,
        'level_min_x_absolute': 0.0,
        'level_min_y_absolute': 0.0,
        'level_max_y_absolute': 1000.0,
        'ground_level_y_ref': 1000.0,
        'ground_platform_height_ref': 40.0,
        'player_start_pos_p2': (170.5, 918.0),
    }
    return game_data

if __name__ == '__main__':
    data = load_map_two_2()
    import json
    print(json.dumps(data, indent=4))